function pkg = problem32AdiabaticCstr()
%PROBLEM32ADIABATICCSTR Return the multiple-steady-state CSTR package.
% =========================================================================
% Javier Berenguer Sabater
% Created: October 4, 2026. Last update: October 4, 2026
% =========================================================================

    pkg.meta = struct('formatVersion',1, ...
        'name',"Problem 32a adiabatic CSTR") ;
    cp = struct('type',"constant",'value',1393.333333, ...
        'unit',"J/(mol*K)") ;
    pkg.components = struct('name',{"A","P"},'Mw',{[],[]}, ...
        'cp',{cp,cp},'hf',{[],[]}) ;
    pkg.reactions.stoich = [-1 1] ;
    pkg.reactions.DH = struct('value',-209,'unit',"kJ/mol") ;
    pkg.reactions.Tref = struct('value',298,'unit',"K") ;
    pkg.reactions.rateUnits = struct('concentration',"mol/m^3",'time',"s") ;
    pkg.reactions.kinetics = struct('type',"powerlaw",'k0',4.48e6, ...
        'Ea',struct('value',7500*8.314,'unit',"J/mol"), ...
        'orders',[1 0],'reverse',[],'expression',"") ;
    pkg.feeds = struct('name',"F1",'phase',"L", ...
        'T',struct('value',298,'unit',"K"), ...
        'P',struct('value',1,'unit',"atm"),'basis',"concentrations", ...
        'values',[3 0],'valuesUnit',"mol/L", ...
        'Q',struct('value',6e-5,'unit',"m^3/s")) ;
    nirp.pkg.validate(pkg) ;
end
