function [names,descriptions] = exampleNames()
%EXAMPLENAMES Return the supported example model names and descriptions.
% =========================================================================
% Javier Berenguer Sabater
% Created: October 2, 2026. Last update: October 2, 2026
% =========================================================================

    names = ["ex1_cstr_isothermal"; "ex2_cstr_adiabatic_cooler"; ...
        "ex3_pfr_adiabatic"; "ex4_problem40b_parallel"; ...
        "ex5_recycle_cstr"; "ex6_adjust_volume"; "ex7_problem44c"] ;
    descriptions = ["Isothermal CSTR"; "Adiabatic CSTR and cooler"; ...
        "Adiabatic PFR"; "Parallel CSTRs (Problem 40b)"; ...
        "CSTR with recycle"; "Adjusted CSTR volume"; ...
        "Adiabatic CSTR comparison (Problem 44c)"] ;
end
