function [names,descriptions] = exampleNames()
%EXAMPLENAMES Return the supported example model names and descriptions.
% =========================================================================
% Javier Berenguer Sabater
% Created: October 2, 2026. Last update: October 3, 2026
% =========================================================================

    names = ["ex1_cstr_isothermal"; "ex2_cstr_adiabatic_cooler"; ...
        "ex3_pfr_adiabatic"; "ex4_problem40b_parallel"; ...
        "ex5_recycle_cstr"; "ex6_adjust_volume"; "ex7_problem44c"; ...
        "ex8_problem37a_series"; "ex9_problem40a_series"; ...
        "ex10_problem42_cstr_pfr"; "ex11_problem42_pfr_cstr"; ...
        "ex12_problem19_adiabatic_pfr"] ;
    descriptions = ["Isothermal CSTR"; "Adiabatic CSTR and cooler"; ...
        "Adiabatic PFR"; "Parallel CSTRs (Problem 40b)"; ...
        "CSTR with recycle"; "Adjusted CSTR volume"; ...
        "Adiabatic CSTR comparison (Problem 44c)"; ...
        "Problem 37a - Two CSTRs in series with two feeds"; ...
        "Problem 40a - Two CSTRs in series"; ...
        "Problem 42 - CSTR then PFR"; ...
        "Problem 42 - PFR then CSTR"; ...
        "Problem 19 - Adiabatic gas PFR"] ;
end
