function [names,descriptions] = exampleNames()
%EXAMPLENAMES Return the supported example model names and descriptions.
% =========================================================================
% Javier Berenguer Sabater
% Created: October 2, 2026. Last update: October 6, 2026
% =========================================================================

    names = ["ex1_cstr_isothermal"; "ex2_cstr_adiabatic_cooler"; ...
        "ex3_pfr_adiabatic"; "ex4_problem40b_parallel"; ...
        "ex5_recycle_cstr"; "ex6_adjust_volume"; "ex7_problem44c"; ...
        "ex8_problem37a_series"; "ex9_problem40a_series"; ...
        "ex10_problem42_cstr_pfr"; "ex11_problem42_pfr_cstr"; ...
        "ex12_problem19_adiabatic_pfr"; ...
        "ex13_problem21a_isothermal_pfr"; ...
        "ex14_problem21b_adiabatic_pfr"; ...
        "ex15_problem27_jacketed_cstr"; ...
        "ex16_problem30_adiabatic_cstr"; ...
        "ex17_problem31_cooled_cstr"; ...
        "ex18_problem44a_volumes"; ...
        "ex19_problem45a_three_cstrs"; ...
        "ex20_problem45b_feed_temperature"; ...
        "ex21_problem17_adiabatic_pfr_volume"; ...
        "ex22_problem18_acetone_cracking"; ...
        "ex23_problem23_butane_isomerization"; ...
        "ex24_problem26_scale_up_cstr"; ...
        "ex25_problem38_parallel_pfrs"; ...
        "ex26_problem40c_pfr_volume"; ...
        "ex27_problem49a_two_adiabatic_cstrs"; ...
        "ex28_problem49b_one_adiabatic_cstr"; ...
        "ex29_problem34d_jacketed_cstr"; ...
        "ex30_problem33b_cooled_gas_cstr"; ...
        "ex31_problem41_three_cstrs"; ...
        "ex32_problem43_pfr_then_cstr"; ...
        "ex33_problem43_cstr_then_pfr"; ...
        "ex34_problem45c_cooled_tanks"; ...
        "ex35_problem28_steam_jacket"; ...
        "ex36_problem36_air_cooled_cstr"; ...
        "ex37_problem20b_adiabatic_reversible_pfr"; ...
        "ex38_problem29_cstr_volume"; ...
        "ex39_problem29_cooling_area"; ...
        "ex40_problem32_three_steady_states"; ...
        "ex41_problem48_cstr_then_adiabatic_pfr"; ...
        "ex42_problem33d_area_for_max_generation"; ...
        "ex43_problem15_number_of_tubes"; ...
        "ex44_problem22_no_oxidation"] ;
    descriptions = ["Isothermal CSTR"; "Adiabatic CSTR and cooler"; ...
        "Adiabatic PFR"; "Parallel CSTRs (Problem 40b)"; ...
        "CSTR with recycle"; "Adjusted CSTR volume"; ...
        "Adiabatic CSTR comparison (Problem 44c)"; ...
        "Problem 37a - Two CSTRs in series with two feeds"; ...
        "Problem 40a - Two CSTRs in series"; ...
        "Problem 42 - CSTR then PFR"; ...
        "Problem 42 - PFR then CSTR"; ...
        "Problem 19 - Adiabatic gas PFR"; ...
        "Problem 21a - Isothermal PFR, adjusted feed T"; ...
        "Problem 21b - Adiabatic PFR, adjusted feed T"; ...
        "Problem 27 - Jacketed CSTR, adjusted feed T"; ...
        "Problem 30 - Mixer and adiabatic CSTR"; ...
        "Problem 31 - Mixer and cooled CSTR"; ...
        "Problem 44a - Adjusted PFR and CSTR volumes"; ...
        "Problem 45a - Three equal adjusted CSTRs"; ...
        "Problem 45b - Adiabatic CSTR, adjusted feed T"; ...
        "Problem 17 - Adiabatic PFR, adjusted volume"; ...
        "Problem 18 - Acetone cracking, adjusted PFR volume"; ...
        "Problem 23 - Butane isomerization, adjusted PFR volume"; ...
        "Problem 26 - Gas CSTR scale-up, adjusted volume"; ...
        "Problem 38 - Two parallel PFRs with one adjusted volume"; ...
        "Problem 40c - Isothermal PFR, adjusted volume"; ...
        "Problem 49a - Two equal adiabatic CSTRs"; ...
        "Problem 49b - One adiabatic CSTR, adjusted volume"; ...
        "Problem 34d - Jacketed Monsanto-reaction CSTR"; ...
        "Problem 33b - Cooled reversible gas CSTR"; ...
        "Problem 41 - Three CSTRs, adjusted feed flow"; ...
        "Problem 43 - PFR then CSTR, adjusted feed flow"; ...
        "Problem 43 - CSTR then PFR, adjusted feed flow"; ...
        "Problem 45c - Cooled tanks, adjusted areas"; ...
        "Problem 28 - Steam-jacketed CSTR"; ...
        "Problem 36 - Air-cooled CSTR, adjusted area"; ...
        "Problem 20b - Adiabatic reversible PFR, adjusted volume"; ...
        "Problem 29a - Isothermal CSTR, adjusted volume"; ...
        "Problem 29b - Cooled CSTR, adjusted area"; ...
        "Problem 32a - Three CSTR steady states (middle branch unstable)"; ...
        "Problem 48 - CSTR then adiabatic PFR, adjusted volumes"; ...
        "Problem 33d - CSTR area at maximum heat generation"; ...
        "Problem 15 - Isothermal gas PFR, number of tubes"; ...
        "Problem 22 - Adiabatic NO oxidation PFR volume"] ;
end
