classdef SplitterDialog < handle
%SPLITTERDIALOG Edit arbitrary Splitter outlets and their fractions.
% =========================================================================
% Javier Berenguer Sabater
% Created: October 2, 2026. Last update: October 3, 2026
% =========================================================================
    properties (SetAccess=private)
        BlockPath;Figure;NameField;FractionTable;ConnectionTable;StatusLabel;DataModel
    end
    methods
        function obj=SplitterDialog(blockPath,varargin),p=inputParser;addParameter(p,'Visible','on');parse(p,varargin{:});obj.BlockPath=getfullname(blockPath);if string(get_param(obj.BlockPath,'System'))~="nirp.blocks.Splitter",error('nirp:flowsheet:invalidBlock','SplitterDialog requires a Splitter block.');end;obj.build(char(string(p.Results.Visible)));obj.load();end
        function delete(obj),if ~isempty(obj.Figure)&&isvalid(obj.Figure),delete(obj.Figure);end,end
        function addOutlet(obj,fraction),if nargin<2,fraction=NaN;end;if size(obj.FractionTable.Data,1)>=20,error('nirp:flowsheet:portLimit','At most 20 outlets are supported.');end;d=obj.FractionTable.Data;d(end+1,:)={sprintf('<missing>'),fraction};obj.FractionTable.Data=d;obj.closeFractions(repmat("specified",1,size(d,1)));end
        function removeOutlet(obj),d=obj.FractionTable.Data;if size(d,1)<=2,error('nirp:flowsheet:invalidPorts','A Splitter requires at least two outlets.');end;d(end,:)=[];obj.FractionTable.Data=d;obj.closeFractions(repmat("specified",1,size(d,1)));end
        function setFractions(obj,fractions),fractions=fractions(:);if numel(fractions)<2||numel(fractions)>20,error('nirp:flowsheet:invalidPorts','A Splitter requires 2 to 20 outlets.');end;d=cell(numel(fractions),2);old=obj.FractionTable.Data;for i=1:numel(fractions),if i<=size(old,1),d{i,1}=old{i,1};else,d{i,1}='<missing>';end;d{i,2}=fractions(i);end;obj.FractionTable.Data=d;obj.closeFractions(repmat("specified",1,numel(fractions)));end
        function values=getValues(obj),values=obj.DataModel;end
        function applied=apply(obj),applied=obj.closeFractions(obj.DataModel.Fractions.origin);if ~applied,return,end;fractions=obj.DataModel.Fractions.value;fractions(obj.DataModel.Fractions.origin=="calculated")=NaN;try,set_param(obj.BlockPath,'Fractions',mat2str(fractions,17));set_param(bdroot(obj.BlockPath),'SimulationCommand','update');obj.StatusLabel.Text='Applied.';obj.refreshConnections();catch exception,obj.StatusLabel.Text=exception.message;applied=false;end,end
        function accept(obj),if obj.apply(),delete(obj);end,end
        function cancel(obj),delete(obj);end
    end
    methods (Static),function dialog=open(blockPath),dialog=nirp.flowsheet.SplitterDialog(blockPath);end,end
    methods (Access=private)
        function build(obj,visible),obj.Figure=uifigure('Name','Splitter','Tag','NirpSplitterDialog','Visible',visible,'Position',[130 90 720 520]);main=uigridlayout(obj.Figure,[4 1],'RowHeight',{38,'1x',25,38},'Padding',[12 10 12 10]);h=uigridlayout(main,[1 3],'ColumnWidth',{60,'1x',160});uilabel(h,'Text','Name','HorizontalAlignment','right');obj.NameField=uieditfield(h,'text','Editable','off');uibutton(h,'Text','Unit conversion helper','ButtonPushedFcn',@(~,~) UnitConverterHelper.launch());tabs=uitabgroup(main);split=uitab(tabs,'Title','Split fractions');connections=uitab(tabs,'Title','Connections');g=uigridlayout(split,[3 3],'RowHeight',{24,'1x',32},'ColumnWidth',{90,90,'1x'});tip=uilabel(g,'Text','One missing fraction is calculated automatically.','FontAngle','italic');tip.Layout.Row=1;tip.Layout.Column=[1 3];obj.FractionTable=uitable(g,'ColumnName',{'Outlet stream','Fraction'},'ColumnEditable',[false true],'CellEditCallback',@(~,event) obj.fractionEdited(event));obj.FractionTable.Layout.Row=2;obj.FractionTable.Layout.Column=[1 3];add=uibutton(g,'Text','Add outlet','ButtonPushedFcn',@(~,~) obj.addOutlet());add.Layout.Row=3;add.Layout.Column=1;remove=uibutton(g,'Text','Remove','ButtonPushedFcn',@(~,~) obj.removeOutlet());remove.Layout.Row=3;remove.Layout.Column=2;cg=uigridlayout(connections,[2 1],'RowHeight',{30,'1x'});uilabel(cg,'Text','Connected material streams (read only)','FontWeight','bold');obj.ConnectionTable=uitable(cg,'ColumnName',{'Direction','Port','Stream'});obj.StatusLabel=uilabel(main,'Text','Ready.','FontAngle','italic');b=uigridlayout(main,[1 4],'ColumnWidth',{'1x',90,90,90});uilabel(b,'Text','');uibutton(b,'Text','OK','ButtonPushedFcn',@(~,~) obj.accept());uibutton(b,'Text','Cancel','ButtonPushedFcn',@(~,~) obj.cancel());uibutton(b,'Text','Apply','ButtonPushedFcn',@(~,~) obj.apply());end
        function load(obj),obj.NameField.Value=get_param(obj.BlockPath,'Name');fractions=str2num(get_param(obj.BlockPath,'Fractions'));obj.setFractions(fractions);obj.refreshConnections();end %#ok<ST2NM>
        function refreshConnections(obj),graph=nirp.flowsheet.topology(bdroot(obj.BlockPath));key=matlab.lang.makeValidName(get_param(obj.BlockPath,'Name'));data=cell(0,3);namesOut=strings(0,1);if isfield(graph.Units,key),x=graph.Units.(key);for i=1:numel(x.Inputs),data(end+1,:)={'Input',i,label(x.Inputs{i})};end;for i=1:numel(x.Outputs),name=label(x.Outputs{i});data(end+1,:)={'Output',i,name};namesOut(i)=string(name);end;end;obj.ConnectionTable.Data=data;table=obj.FractionTable.Data;for i=1:size(table,1),if i<=numel(namesOut),table{i,1}=char(namesOut(i));else,table{i,1}='<missing>';end;end;obj.FractionTable.Data=table;end
        function fractionEdited(obj,event),origin=obj.DataModel.Fractions.origin;row=event.Indices(1);origin(row)="specified";values=obj.readFractions();values(origin=="calculated")=NaN;obj.writeFractions(values);obj.closeFractions(origin);end
        function valid=closeFractions(obj,origin),values=obj.readFractions();if numel(origin)==numel(values),values(origin=="calculated")=NaN;end;[values,newOrigin,message]=nirp.flowsheet.closeSum(values,1);obj.writeFractions(values);obj.DataModel=struct('Fractions',struct('value',values,'unit',"1",'origin',newOrigin));obj.showOrigins(newOrigin);valid=strlength(message)==0&&all(isfinite(values));if strlength(message)>0,obj.StatusLabel.Text=char(message);elseif valid,obj.StatusLabel.Text='Fractions are complete.';else,obj.StatusLabel.Text='';obj.showMissing(values);end,end
        function values=readFractions(obj),d=obj.FractionTable.Data;values=NaN(1,size(d,1));for i=1:size(d,1),v=d{i,2};if isnumeric(v)&&isscalar(v)&&~isempty(v),values(i)=v;elseif ischar(v)||isstring(v),parsed=str2double(v);if isscalar(parsed),values(i)=parsed;end,end,end,end
        function writeFractions(obj,values),d=obj.FractionTable.Data;for i=1:numel(values),if isnan(values(i)),d{i,2}=[];else,d{i,2}=values(i);end,end;obj.FractionTable.Data=d;end
        function showOrigins(obj,origin),removeStyle(obj.FractionTable);rows=find(origin=="calculated");if ~isempty(rows),style=uistyle('FontAngle','italic','BackgroundColor',[0.92 0.92 0.92]);addStyle(obj.FractionTable,style,'cell',[rows(:) repmat(2,numel(rows),1)]);end,end
        function showMissing(obj,values),rows=find(isnan(values));if ~isempty(rows),style=uistyle('BackgroundColor',[1 0.86 0.86]);addStyle(obj.FractionTable,style,'cell',[rows(:) repmat(2,numel(rows),1)]);end,end
    end
end
function s=label(v),if isempty(v),s='<missing>';else,s=char(strjoin(string(v),', '));end,end
