function modelFiles = build_examples(folder,only)
%BUILD_EXAMPLES Generate the milestone-1 NIRP example flowsheets.
% =========================================================================
% Javier Berenguer Sabater
% Created: October 2, 2026. Last update: October 10, 2026
%   BUILD_EXAMPLES(FOLDER,ONLY) builds only the examples named in ONLY (T-143).
% =========================================================================

    repoRoot=fileparts(fileparts(mfilename('fullpath'))); addpath(repoRoot);
    if nargin<1||isempty(folder),folder=fullfile(fileparts(mfilename('fullpath')),'examples');end
    if ~isfolder(folder),mkdir(folder);end
    if ~contains([path pathsep],[folder pathsep]),addpath(folder);end
    referencePkg=firstOrderReferencePackage();
    definitions={ ...
        'ex1_cstr_isothermal',referencePkg,@buildEx1; ...
        'ex2_cstr_adiabatic_cooler',referencePkg,@buildEx2; ...
        'ex3_pfr_adiabatic',referencePkg,@buildEx3; ...
        'ex4_problem40b_parallel',nirp.pkg.examples.problem40Gas(),@buildEx4; ...
        'ex5_recycle_cstr',referencePkg,@buildEx5; ...
        'ex6_adjust_volume',referencePkg,@buildEx6; ...
        'ex7_problem44c',nirp.pkg.examples.problem44Liquid(),@buildEx7; ...
        'ex8_problem37a_series',nirp.pkg.examples.problem37Liquid(),@buildEx8; ...
        'ex9_problem40a_series',nirp.pkg.examples.problem40Gas(),@buildEx9; ...
        'ex10_problem42_cstr_pfr',nirp.pkg.examples.problem42SecondOrder(),@buildEx10; ...
        'ex11_problem42_pfr_cstr',nirp.pkg.examples.problem42SecondOrder(),@buildEx11; ...
        'ex12_problem19_adiabatic_pfr',nirp.pkg.examples.problem19Gas(),@buildEx12; ...
        'ex13_problem21a_isothermal_pfr',nirp.pkg.examples.problem21Gas(),@buildEx13; ...
        'ex14_problem21b_adiabatic_pfr',nirp.pkg.examples.problem21Gas(),@buildEx14; ...
        'ex15_problem27_jacketed_cstr',nirp.pkg.examples.problem27Jacketed(),@buildEx15; ...
        'ex16_problem30_adiabatic_cstr',nirp.pkg.examples.problem30Liquid(),@buildEx16; ...
        'ex17_problem31_cooled_cstr',nirp.pkg.examples.problem30Liquid(),@buildEx17; ...
        'ex18_problem44a_volumes',nirp.pkg.examples.problem44Liquid(),@buildEx18; ...
        'ex19_problem45a_three_cstrs',nirp.pkg.examples.problem45Liquid(),@buildEx19; ...
        'ex20_problem45b_feed_temperature',nirp.pkg.examples.problem45Liquid(),@buildEx20; ...
        'ex21_problem17_adiabatic_pfr_volume',nirp.pkg.examples.problem17AdiabaticGas(),@buildEx21; ...
        'ex22_problem18_acetone_cracking',nirp.pkg.examples.problem18AcetoneCracking(),@buildEx22; ...
        'ex23_problem23_butane_isomerization',nirp.pkg.examples.problem23ButaneIsomerization(),@buildEx23; ...
        'ex24_problem26_scale_up_cstr',nirp.pkg.examples.problem26ScaleUpGas(),@buildEx24; ...
        'ex25_problem38_parallel_pfrs',nirp.pkg.examples.problem38ParallelGas(),@buildEx25; ...
        'ex26_problem40c_pfr_volume',nirp.pkg.examples.problem40cGas(),@buildEx26; ...
        'ex27_problem49a_two_adiabatic_cstrs',nirp.pkg.examples.problem49AdiabaticLiquid(),@buildEx27; ...
        'ex28_problem49b_one_adiabatic_cstr',nirp.pkg.examples.problem49AdiabaticLiquid(),@buildEx28; ...
        'ex29_problem34d_jacketed_cstr',nirp.pkg.examples.problem34dMonsanto(),@buildEx29; ...
        'ex30_problem33b_cooled_gas_cstr',nirp.pkg.examples.problem33Gas(),@buildEx30; ...
        'ex31_problem41_three_cstrs',nirp.pkg.examples.problem41SecondOrder(),@buildEx31; ...
        'ex32_problem43_pfr_then_cstr',nirp.pkg.examples.problem43Liquid(),@buildEx32; ...
        'ex33_problem43_cstr_then_pfr',nirp.pkg.examples.problem43Liquid(),@buildEx33; ...
        'ex34_problem45c_cooled_tanks',nirp.pkg.examples.problem45Liquid(),@buildEx34; ...
        'ex35_problem28_steam_jacket',nirp.pkg.examples.problem28SteamJacket(),@buildEx35; ...
        'ex36_problem36_air_cooled_cstr',nirp.pkg.examples.problem36AirCooled(),@buildEx36; ...
        'ex37_problem20b_adiabatic_reversible_pfr',nirp.pkg.examples.problem33Gas(),@buildEx37; ...
        'ex38_problem29_cstr_volume',nirp.pkg.examples.problem29Hydrolysis(),@buildEx38; ...
        'ex39_problem29_cooling_area',nirp.pkg.examples.problem29Hydrolysis(),@buildEx39; ...
        'ex40_problem32_three_steady_states',nirp.pkg.examples.problem32AdiabaticCstr(),@buildEx40; ...
        'ex41_problem48_cstr_then_adiabatic_pfr',nirp.pkg.examples.problem48ReversibleGas(),@buildEx41; ...
        'ex42_problem33d_area_for_max_generation',nirp.pkg.examples.problem33Gas(),@buildEx42; ...
        'ex43_problem15_number_of_tubes',nirp.pkg.examples.problem15Acetylene(),@buildEx43; ...
        'ex44_problem22_no_oxidation',nirp.pkg.examples.problem22NOOxidation(),@buildEx44; ...
        'ex45_problem16_pfr_space_time',nirp.pkg.examples.problem16EmpiricalGas(),@buildEx45; ...
        'ex46_problem35_isothermal_cstr',nirp.pkg.examples.problem35NOReduction(),@buildEx46; ...
        'ex47_problem35_adiabatic_feed_T',nirp.pkg.examples.problem35NOReduction(),@buildEx47; ...
        'ex48_recycle_pfr',referencePkg,@buildEx48; ...
        'ex49_reactor_separator_recycle',referencePkg,@buildEx49; ...
        'ex50_recycle_with_adjust',referencePkg,@buildEx50};
    if nargin>=2&&~isempty(only),definitions=definitions(ismember(string(definitions(:,1)),string(only)),:);end
    modelFiles=strings(size(definitions,1),1);
    for i=1:size(definitions,1)
        name=definitions{i,1}; pkg=definitions{i,2}; builder=definitions{i,3};
        modelFile=fullfile(folder,[name '.slx']); dictionaryFile=fullfile(folder,[name '.sldd']);
        if bdIsLoaded(name),close_system(name,0);end
        if isfile(modelFile),delete(modelFile);end
        if isfile(dictionaryFile),delete(dictionaryFile);end
        nirp.pkg.writeDictionary(pkg,dictionaryFile); new_system(name); save_system(name,modelFile);
        set_param(name,'DataDictionary',[name '.sldd']);
        nirp.flowsheet.addBlock(name,'Flowsheet',[20 20 140 75],200);
        builder(name); routeSignalLines(name); nirp.flowsheet.configure(name);
        save_system(name,modelFile); close_system(name,0); modelFiles(i)=string(modelFile);
        Simulink.data.dictionary.closeAll('-discard');
    end
end

function pkg=firstOrderReferencePackage()
    % T-101 base data (k = 0.6 1/min = 0.01 1/s) straight from the template.
    pkg=nirp.pkg.examples.firstOrderLiquid();
    nirp.pkg.validate(pkg);
end

function buildEx1(model)
    addSystem(model,'F1','nirp.blocks.Stream',[40 120 160 170],'Role','Feed');
    addSystem(model,'CSTR','nirp.blocks.CSTR',[200 110 320 180],'V','100','VUnit','L','HeatMode','Isothermal');
    addSystem(model,'Product','nirp.blocks.Stream',[390 120 520 170], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A');
    add_line(model,'F1/1','CSTR/1'); add_line(model,'CSTR/1','Product/1');
end

function buildEx2(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 120 130 170],'Role','Feed');
    addSystem(model,'CSTR','nirp.blocks.CSTR',[180 110 300 180],'V','100','VUnit','L','HeatMode','Adiabatic');
    addSystem(model,'CSTR outlet','nirp.blocks.Stream',[340 120 460 170],'Role','Intermediate');
    addSystem(model,'Cooler','nirp.blocks.Heater',[510 110 630 180],'Mode','Outlet T','Tout','300','ToutUnit','K','ShowHeatPort','on');
    addSystem(model,'Product','nirp.blocks.Stream',[690 120 810 170],'Role','Product','ReferenceFeed','F1','KeyComponent','A');
    add_block('simulink/Sinks/Terminator',[model '/Cooler duty'],'Position',[680 205 700 225]);
    add_line(model,'F1/1','CSTR/1');add_line(model,'CSTR/1','CSTR outlet/1');add_line(model,'CSTR outlet/1','Cooler/1');add_line(model,'Cooler/1','Product/1');add_line(model,'Cooler/2','Cooler duty/1');
end

function buildEx3(model)
    addSystem(model,'F1','nirp.blocks.Stream',[40 120 160 170],'Role','Feed');
    addSystem(model,'PFR','nirp.blocks.PFR',[200 105 330 185],'GeometryMode','Volume','V','0.1','VUnit','m^3','D','0.1','DUnit','m','HeatMode','Adiabatic');
    addSystem(model,'Product','nirp.blocks.Stream',[400 120 530 170],'Role','Product','ReferenceFeed','F1','KeyComponent','A');
    add_line(model,'F1/1','PFR/1');add_line(model,'PFR/1','Product/1');
end

function buildEx4(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 180 130 230],'Role','Feed');
    addSystem(model,'Splitter','nirp.blocks.Splitter',[160 165 270 245],'Fractions','[0.5 0.5]');
    addSystem(model,'Branch 1','nirp.blocks.Stream',[310 90 420 140],'Role','Intermediate');
    addSystem(model,'Branch 2','nirp.blocks.Stream',[310 275 420 325],'Role','Intermediate');
    addSystem(model,'CSTR 1','nirp.blocks.CSTR',[460 80 580 150],'V','400','VUnit','L','HeatMode','Isothermal');
    addSystem(model,'CSTR 2','nirp.blocks.CSTR',[460 265 580 335],'V','400','VUnit','L','HeatMode','Isothermal');
    addSystem(model,'CSTR 1 outlet','nirp.blocks.Stream',[620 90 750 140],'Role','Intermediate');
    addSystem(model,'CSTR 2 outlet','nirp.blocks.Stream',[620 275 750 325],'Role','Intermediate');
    addSystem(model,'Mixer','nirp.blocks.Mixer',[790 165 900 245],'NumInputs','2');
    addSystem(model,'Product','nirp.blocks.Stream',[950 180 1070 230],'Role','Product','ReferenceFeed','F1','KeyComponent','A');
    add_line(model,'F1/1','Splitter/1');add_line(model,'Splitter/1','Branch 1/1');add_line(model,'Splitter/2','Branch 2/1');
    add_line(model,'Branch 1/1','CSTR 1/1');add_line(model,'Branch 2/1','CSTR 2/1');
    add_line(model,'CSTR 1/1','CSTR 1 outlet/1');add_line(model,'CSTR 2/1','CSTR 2 outlet/1');
    add_line(model,'CSTR 1 outlet/1','Mixer/1');add_line(model,'CSTR 2 outlet/1','Mixer/2');add_line(model,'Mixer/1','Product/1');
end

function buildEx5(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 160 130 215],'Role','Feed');
    addSystem(model,'Mixer','nirp.blocks.Mixer',[180 145 310 225],'NumInputs','2');
    addSystem(model,'Mixer outlet','nirp.blocks.Stream',[350 160 470 215],'Role','Intermediate');
    addSystem(model,'CSTR','nirp.blocks.CSTR',[510 150 640 220],'V','0.1','VUnit','m^3');
    addSystem(model,'CSTR outlet','nirp.blocks.Stream',[680 160 800 215],'Role','Intermediate');
    addSystem(model,'Splitter','nirp.blocks.Splitter',[840 140 970 230],'Fractions','[0.1 0.9]');
    addSystem(model,'Recycle feed','nirp.blocks.Stream',[790 300 920 355],'Role','Intermediate','Orientation','left');
    addSystem(model,'Recycle','nirp.blocks.Recycle',[570 300 720 365], ...
        'Method','Wegstein','Orientation','left');
    addSystem(model,'Recycle outlet','nirp.blocks.Stream',[350 300 490 355],'Role','Intermediate','Orientation','left');
    addSystem(model,'Product','nirp.blocks.Stream',[1020 150 1150 220], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A');
    add_line(model,'F1/1','Mixer/1','autorouting','on');
    add_line(model,'Recycle outlet/1','Mixer/2','autorouting','on');
    add_line(model,'Mixer/1','Mixer outlet/1','autorouting','on');
    add_line(model,'Mixer outlet/1','CSTR/1','autorouting','on');
    add_line(model,'CSTR/1','CSTR outlet/1','autorouting','on');
    add_line(model,'CSTR outlet/1','Splitter/1','autorouting','on');
    add_line(model,'Splitter/1','Product/1','autorouting','on');
    add_line(model,'Splitter/2','Recycle feed/1','autorouting','on');
    add_line(model,'Recycle feed/1','Recycle/1','autorouting','on');
    add_line(model,'Recycle/1','Recycle outlet/1','autorouting','on');
end

function buildEx48(model)
    % T-143: isothermal PFR with recycle ratio R = 1 (Levenspiel reference).
    addSystem(model,'F1','nirp.blocks.Stream',[20 160 130 215],'Role','Feed');
    addSystem(model,'Mixer','nirp.blocks.Mixer',[180 145 310 225],'NumInputs','2');
    addSystem(model,'Mixer outlet','nirp.blocks.Stream',[350 160 470 215],'Role','Intermediate');
    addSystem(model,'PFR','nirp.blocks.PFR',[510 150 640 220],'GeometryMode','Volume','V','0.1','VUnit','m^3', ...
        'D','0.1','DUnit','m','HeatMode','Isothermal');
    addSystem(model,'PFR outlet','nirp.blocks.Stream',[680 160 800 215],'Role','Intermediate');
    addSystem(model,'Splitter','nirp.blocks.Splitter',[840 140 970 230],'Fractions','[0.5 0.5]');
    addSystem(model,'Recycle feed','nirp.blocks.Stream',[790 300 920 355],'Role','Intermediate','Orientation','left');
    addSystem(model,'Recycle','nirp.blocks.Recycle',[570 300 720 365],'Method','Wegstein','Orientation','left');
    addSystem(model,'Recycle outlet','nirp.blocks.Stream',[350 300 490 355],'Role','Intermediate','Orientation','left');
    addSystem(model,'Product','nirp.blocks.Stream',[1020 150 1150 220],'Role','Product','ReferenceFeed','F1','KeyComponent','A');
    add_line(model,'F1/1','Mixer/1','autorouting','on');add_line(model,'Recycle outlet/1','Mixer/2','autorouting','on');
    add_line(model,'Mixer/1','Mixer outlet/1','autorouting','on');add_line(model,'Mixer outlet/1','PFR/1','autorouting','on');
    add_line(model,'PFR/1','PFR outlet/1','autorouting','on');add_line(model,'PFR outlet/1','Splitter/1','autorouting','on');
    add_line(model,'Splitter/1','Product/1','autorouting','on');add_line(model,'Splitter/2','Recycle feed/1','autorouting','on');
    add_line(model,'Recycle feed/1','Recycle/1','autorouting','on');add_line(model,'Recycle/1','Recycle outlet/1','autorouting','on');
end

function buildEx49(model)
    % T-143: CSTR -> component separator -> recycle of unconverted A with a 10 % purge.
    buildSeparatorLoop(model,{'V','0.1','VUnit','m^3','HeatMode','Isothermal'});
end

function buildEx50(model)
    % T-143: the ex49 loop with an Adjust that moves the CSTR volume for a 0.95 overall conversion.
    % The Simultaneous strategy oscillates here (neither block converges in 200 iterations);
    % Nested converges the Recycle for every Adjust step (V = 0.160 m^3).
    buildSeparatorLoop(model,{'VSource','Input port','VUnit','m^3','HeatMode','Isothermal'});
    addSystem(model,'Adjust','nirp.blocks.Adjust',[400 430 570 500], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.95','InitialValue','0.1','MinValue','0.001', ...
        'MaxValue','10','ParameterUnit','m^3','Strategy','Nested','Orientation','left');
    add_line(model,'Adjust/1','CSTR/2','autorouting','on');add_line(model,'Separator/2','Adjust/1','autorouting','on');
end

function buildSeparatorLoop(model,reactorArgs)
    addSystem(model,'F1','nirp.blocks.Stream',[20 160 130 215],'Role','Feed');
    addSystem(model,'Mixer','nirp.blocks.Mixer',[170 145 290 225],'NumInputs','2');
    addSystem(model,'Mixer outlet','nirp.blocks.Stream',[320 160 430 215],'Role','Intermediate');
    addSystem(model,'CSTR','nirp.blocks.CSTR',[470 150 590 220],reactorArgs{:});
    addSystem(model,'CSTR outlet','nirp.blocks.Stream',[620 160 730 215],'Role','Intermediate');
    addSystem(model,'Separator','nirp.blocks.Separator',[770 145 890 225],'Recovery','[0.95 0.02]');
    addSystem(model,'Separator top','nirp.blocks.Stream',[930 60 1040 115],'Role','Intermediate');
    addSystem(model,'Purge splitter','nirp.blocks.Splitter',[1080 50 1190 130],'Fractions','[0.1 0.9]');
    addSystem(model,'Purge','nirp.blocks.Stream',[1230 30 1340 85],'Role','Product');
    addSystem(model,'Recycle feed','nirp.blocks.Stream',[1100 300 1210 355],'Role','Intermediate','Orientation','left');
    addSystem(model,'Recycle','nirp.blocks.Recycle',[700 300 850 365],'Method','Wegstein','Orientation','left');
    addSystem(model,'Recycle outlet','nirp.blocks.Stream',[320 300 450 355],'Role','Intermediate','Orientation','left');
    addSystem(model,'Product','nirp.blocks.Stream',[930 200 1050 255],'Role','Product','ReferenceFeed','F1','KeyComponent','A');
    add_line(model,'F1/1','Mixer/1','autorouting','on');add_line(model,'Recycle outlet/1','Mixer/2','autorouting','on');
    add_line(model,'Mixer/1','Mixer outlet/1','autorouting','on');add_line(model,'Mixer outlet/1','CSTR/1','autorouting','on');
    add_line(model,'CSTR/1','CSTR outlet/1','autorouting','on');add_line(model,'CSTR outlet/1','Separator/1','autorouting','on');
    add_line(model,'Separator/1','Separator top/1','autorouting','on');add_line(model,'Separator/2','Product/1','autorouting','on');
    add_line(model,'Separator top/1','Purge splitter/1','autorouting','on');add_line(model,'Purge splitter/1','Purge/1','autorouting','on');
    add_line(model,'Purge splitter/2','Recycle feed/1','autorouting','on');add_line(model,'Recycle feed/1','Recycle/1','autorouting','on');
    add_line(model,'Recycle/1','Recycle outlet/1','autorouting','on');
end

function buildEx6(model)
    addSystem(model,'F1','nirp.blocks.Stream',[30 150 140 200],'Role','Feed');
    addSystem(model,'CSTR','nirp.blocks.CSTR',[280 135 410 210], ...
        'VSource','Input port','HeatMode','Isothermal');
    addSystem(model,'Adjust','nirp.blocks.Adjust',[60 280 230 350], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.8','InitialValue','0.1','MinValue','0.001', ...
        'MaxValue','1','ParameterUnit','m^3');
    addSystem(model,'Product','nirp.blocks.Stream',[500 150 630 200], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A');
    add_line(model,'F1/1','CSTR/1');add_line(model,'Adjust/1','CSTR/2');
    add_line(model,'CSTR/1','Adjust/1');add_line(model,'CSTR/1','Product/1');
end

function buildEx7(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 210 130 260],'Role','Feed');
    addSystem(model,'CSTR 500 L','nirp.blocks.CSTR',[190 90 330 165], ...
        'V','500','VUnit','L','HeatMode','Adiabatic','InitialTGuess','495','InitialTGuessUnit','K');
    addSystem(model,'CSTR 250 L 1','nirp.blocks.CSTR',[190 300 330 375], ...
        'V','250','VUnit','L','HeatMode','Adiabatic','InitialTGuess','490','InitialTGuessUnit','K');
    addSystem(model,'CSTR 250 L 2','nirp.blocks.CSTR',[400 300 540 375], ...
        'V','250','VUnit','L','HeatMode','Adiabatic','InitialTGuess','499','InitialTGuessUnit','K');
    addSystem(model,'Product500','nirp.blocks.Stream',[650 100 780 155], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A');
    addSystem(model,'Series intermediate','nirp.blocks.Stream',[370 300 520 355],'Role','Intermediate');
    addSystem(model,'ProductSeries','nirp.blocks.Stream',[650 310 790 365], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A');
    add_line(model,'F1/1','CSTR 500 L/1');add_line(model,'CSTR 500 L/1','Product500/1');
    add_line(model,'F1/1','CSTR 250 L 1/1');add_line(model,'CSTR 250 L 1/1','Series intermediate/1');
    add_line(model,'Series intermediate/1','CSTR 250 L 2/1');
    add_line(model,'CSTR 250 L 2/1','ProductSeries/1');
end

function buildEx8(model)
    addSystem(model,'Feed A','nirp.blocks.Stream',[20 90 140 140],'Role','Feed');
    addSystem(model,'Feed B','nirp.blocks.Stream',[20 230 140 280],'Role','Feed');
    addSystem(model,'Mixer','nirp.blocks.Mixer',[190 135 310 225],'NumInputs','2');
    addSystem(model,'Mixed feed','nirp.blocks.Stream',[350 155 480 205],'Role','Intermediate');
    addSystem(model,'CSTR 1','nirp.blocks.CSTR',[520 145 640 215], ...
        'V','200','VUnit','L','HeatMode','Isothermal');
    addSystem(model,'CSTR 1 outlet','nirp.blocks.Stream',[680 155 820 205],'Role','Intermediate');
    addSystem(model,'CSTR 2','nirp.blocks.CSTR',[860 145 980 215], ...
        'V','200','VUnit','L','HeatMode','Isothermal');
    addSystem(model,'Product','nirp.blocks.Stream',[1020 155 1150 205], ...
        'Role','Product','ReferenceFeed','Feed A','KeyComponent','A');
    add_line(model,'Feed A/1','Mixer/1');add_line(model,'Feed B/1','Mixer/2');
    add_line(model,'Mixer/1','Mixed feed/1');add_line(model,'Mixed feed/1','CSTR 1/1');
    add_line(model,'CSTR 1/1','CSTR 1 outlet/1');add_line(model,'CSTR 1 outlet/1','CSTR 2/1');
    add_line(model,'CSTR 2/1','Product/1');
end

function buildEx9(model)
    addSystem(model,'F1','nirp.blocks.Stream',[30 120 150 170],'Role','Feed');
    addSystem(model,'CSTR 1','nirp.blocks.CSTR',[200 110 320 180], ...
        'V','400','VUnit','L','HeatMode','Isothermal');
    addSystem(model,'CSTR 1 outlet','nirp.blocks.Stream',[360 120 500 170],'Role','Intermediate');
    addSystem(model,'CSTR 2','nirp.blocks.CSTR',[540 110 660 180], ...
        'V','400','VUnit','L','HeatMode','Isothermal');
    addSystem(model,'Product','nirp.blocks.Stream',[710 120 840 170], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A');
    add_line(model,'F1/1','CSTR 1/1');add_line(model,'CSTR 1/1','CSTR 1 outlet/1');
    add_line(model,'CSTR 1 outlet/1','CSTR 2/1');add_line(model,'CSTR 2/1','Product/1');
end

function buildEx10(model)
    buildProblem42Train(model,'CSTR','PFR');
end

function buildEx11(model)
    buildProblem42Train(model,'PFR','CSTR');
end

function buildProblem42Train(model,firstType,secondType)
    addSystem(model,'F1','nirp.blocks.Stream',[30 120 150 170],'Role','Feed');
    addProblem42Reactor(model,[firstType ' 1'],firstType,[200 105 330 185]);
    addSystem(model,'Intermediate','nirp.blocks.Stream',[370 120 500 170],'Role','Intermediate');
    addProblem42Reactor(model,[secondType ' 2'],secondType,[540 105 670 185]);
    addSystem(model,'Product','nirp.blocks.Stream',[720 120 850 170], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A');
    add_line(model,'F1/1',[firstType ' 1/1']);
    add_line(model,[firstType ' 1/1'],'Intermediate/1');
    add_line(model,'Intermediate/1',[secondType ' 2/1']);
    add_line(model,[secondType ' 2/1'],'Product/1');
end

function addProblem42Reactor(model,name,type,position)
    if strcmp(type,'PFR')
        addSystem(model,name,'nirp.blocks.PFR',position,'GeometryMode','Volume', ...
            'V','1','VUnit','m^3','D','0.1','DUnit','m','HeatMode','Isothermal');
    else
        addSystem(model,name,'nirp.blocks.CSTR',position, ...
            'V','1','VUnit','m^3','HeatMode','Isothermal');
    end
end

function buildEx12(model)
    addSystem(model,'F1','nirp.blocks.Stream',[40 120 160 170],'Role','Feed');
    addSystem(model,'PFR','nirp.blocks.PFR',[210 105 350 185], ...
        'GeometryMode','Volume','V','1.5','VUnit','m^3','D','0.1', ...
        'DUnit','m','HeatMode','Adiabatic');
    addSystem(model,'Product','nirp.blocks.Stream',[400 120 540 170], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A');
    add_line(model,'F1/1','PFR/1');add_line(model,'PFR/1','Product/1');
end

function buildEx13(model)
    buildProblem21(model,'Isothermal',380,330,450) ;
end

function buildEx14(model)
    buildProblem21(model,'Adiabatic',430,380,520) ;
end

function buildProblem21(model,heatMode,initialValue,minimum,maximum)
    addSystem(model,'F1','nirp.blocks.Stream',[250 120 380 170], ...
        'Role','Feed','TSource','Input port') ;
    addSystem(model,'PFR','nirp.blocks.PFR',[440 105 580 185], ...
        'GeometryMode','Volume','V','1000','VUnit','L','D','0.1', ...
        'DUnit','m','HeatMode',heatMode) ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[20 250 300 320], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.9','InitialValue',num2str(initialValue), ...
        'MinValue',num2str(minimum),'MaxValue',num2str(maximum), ...
        'ParameterUnit','K','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[650 120 790 170], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'Adjust/1','F1/1') ; add_line(model,'F1/1','PFR/1') ;
    add_line(model,'PFR/1','Adjust/1') ; add_line(model,'PFR/1','Product/1') ;
end

function buildEx15(model)
    addSystem(model,'F1','nirp.blocks.Stream',[250 120 380 170], ...
        'Role','Feed','TSource','Input port') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[440 105 580 185], ...
        'V','200','VUnit','L','HeatMode','Heat exchange') ;
    addSystem(model,'Jacket','nirp.blocks.Jacket',[440 5 580 70], ...
        'U','300','UUnit','W/(m^2*K)','A','9','AUnit','m^2', ...
        'UtilityTin','273','UtilityTinUnit','K','UtilityTout','NaN') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[20 250 300 320], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.8','InitialValue','295','MinValue','285', ...
        'MaxValue','305','ParameterUnit','K','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[650 120 790 170], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'Adjust/1','F1/1') ; add_line(model,'F1/1','CSTR/1') ;add_line(model,'Jacket/1','CSTR/2') ;
    add_line(model,'CSTR/1','Adjust/1') ; add_line(model,'CSTR/1','Product/1') ;
end

function buildEx16(model)
    buildProblem30(model,'Adiabatic') ;
end

function buildEx17(model)
    buildProblem30(model,'Heat exchange') ;
end

function buildProblem30(model,heatMode)
    addSystem(model,'Feed PO','nirp.blocks.Stream',[20 90 150 140],'Role','Feed') ;
    addSystem(model,'Feed W','nirp.blocks.Stream',[20 230 150 280],'Role','Feed') ;
    addSystem(model,'Mixer','nirp.blocks.Mixer',[200 135 320 225],'NumInputs','2') ;
    addSystem(model,'Mixed feed','nirp.blocks.Stream',[360 155 490 205], ...
        'Role','Intermediate') ;
    reactorArgs = {'V','1.136','VUnit','m^3','HeatMode',heatMode} ;
    if strcmp(heatMode,'Heat exchange')
        reactorArgs = {'V','1.136','VUnit','m^3','HeatMode','Heat exchange'} ;
        addSystem(model,'Jacket','nirp.blocks.Jacket',[540 45 680 110], ...
            'U','567.7','UUnit','W/(m^2*K)','A','3.7','AUnit','m^2', ...
            'UtilityTin','29.5','UtilityTinUnit',[char(176) 'C'],'UtilityTout','NaN') ;
    end
    addSystem(model,'CSTR','nirp.blocks.CSTR',[540 145 680 215],reactorArgs{:}) ;
    addSystem(model,'Product','nirp.blocks.Stream',[730 155 870 205], ...
        'Role','Product','ReferenceFeed','Feed PO','KeyComponent','PO') ;
    add_line(model,'Feed PO/1','Mixer/1') ; add_line(model,'Feed W/1','Mixer/2') ;
    add_line(model,'Mixer/1','Mixed feed/1') ; add_line(model,'Mixed feed/1','CSTR/1') ;
    if strcmp(heatMode,'Heat exchange'),add_line(model,'Jacket/1','CSTR/2');end
    add_line(model,'CSTR/1','Product/1') ;
end

function buildEx18(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 255 140 305],'Role','Feed') ;
    addSystem(model,'PFR','nirp.blocks.PFR',[380 160 520 240], ...
        'GeometryMode','Volume','VSource','Input port','D','0.1', ...
        'DUnit','m','HeatMode','Adiabatic') ;
    addSystem(model,'Adjust PFR','nirp.blocks.Adjust',[330 20 610 90], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.85','InitialValue','20','MinValue','5', ...
        'MaxValue','100','ParameterUnit','L','Tolerance','1e-10') ;
    addSystem(model,'Product PFR','nirp.blocks.Stream',[680 175 830 225], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[380 330 520 405], ...
        'VSource','Input port','HeatMode','Adiabatic') ;
    addSystem(model,'Adjust CSTR','nirp.blocks.Adjust',[330 470 610 540], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.85','InitialValue','15','MinValue','10', ...
        'MaxValue','30','ParameterUnit','L','Tolerance','1e-10') ;
    addSystem(model,'Product CSTR','nirp.blocks.Stream',[680 345 830 395], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'F1/1','PFR/1') ; add_line(model,'Adjust PFR/1','PFR/2') ;
    add_line(model,'PFR/1','Adjust PFR/1') ; add_line(model,'PFR/1','Product PFR/1') ;
    add_line(model,'F1/1','CSTR/1') ; add_line(model,'Adjust CSTR/1','CSTR/2') ;
    add_line(model,'CSTR/1','Adjust CSTR/1') ; add_line(model,'CSTR/1','Product CSTR/1') ;
end

function buildEx19(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'CSTR 1','nirp.blocks.CSTR',[370 120 510 195], ...
        'VSource','Input port','HeatMode','Isothermal') ;
    addSystem(model,'CSTR 1 outlet','nirp.blocks.Stream',[550 135 690 185], ...
        'Role','Intermediate') ;
    addSystem(model,'CSTR 2','nirp.blocks.CSTR',[730 120 870 195], ...
        'VSource','Input port','HeatMode','Isothermal') ;
    addSystem(model,'CSTR 2 outlet','nirp.blocks.Stream',[910 135 1050 185], ...
        'Role','Intermediate') ;
    addSystem(model,'CSTR 3','nirp.blocks.CSTR',[1090 120 1230 195], ...
        'VSource','Input port','HeatMode','Isothermal') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[40 270 320 340], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.9','InitialValue','200','MinValue','100', ...
        'MaxValue','500','ParameterUnit','L','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[1280 135 1420 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'F1/1','CSTR 1/1') ; add_line(model,'Adjust/1','CSTR 1/2') ;
    add_line(model,'CSTR 1/1','CSTR 1 outlet/1') ;
    add_line(model,'CSTR 1 outlet/1','CSTR 2/1') ; add_line(model,'Adjust/1','CSTR 2/2') ;
    add_line(model,'CSTR 2/1','CSTR 2 outlet/1') ;
    add_line(model,'CSTR 2 outlet/1','CSTR 3/1') ; add_line(model,'Adjust/1','CSTR 3/2') ;
    add_line(model,'CSTR 3/1','Adjust/1') ; add_line(model,'CSTR 3/1','Product/1') ;
end

function buildEx20(model)
    addSystem(model,'F1','nirp.blocks.Stream',[250 120 380 170], ...
        'Role','Feed','TSource','Input port') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[440 105 580 185], ...
        'V','250.480335','VUnit','L','HeatMode','Adiabatic') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[20 250 300 320], ...
        'TargetVariable','Temperature','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','95','TargetUnit',[char(176) 'C'], ...
        'InitialValue','345','MinValue','335','MaxValue','355', ...
        'ParameterUnit','K','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[650 120 790 170], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'Adjust/1','F1/1') ; add_line(model,'F1/1','CSTR/1') ;
    add_line(model,'CSTR/1','Adjust/1') ; add_line(model,'CSTR/1','Product/1') ;
end

function buildEx21(model)
    buildAdjustedPfr(model,'A',0.35,10,1,100,'L','Adiabatic') ;
end

function buildEx22(model)
    buildAdjustedPfr(model,'Acetone',0.2,1,0.1,10,'m^3','Adiabatic') ;
end

function buildEx23(model)
    buildAdjustedPfr(model,'n-C4',0.65,1,0.2,5,'m^3','Adiabatic') ;
end

function buildEx24(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[370 120 510 195], ...
        'VSource','Input port','HeatMode','Isothermal') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[40 270 320 340], ...
        'TargetVariable','Conversion','KeyComponent','Acetaldehyde', ...
        'ReferenceFeed','F1','TargetValue','0.75','InitialValue','500', ...
        'MinValue','100','MaxValue','3000','ParameterUnit','m^3', ...
        'Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[570 135 710 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','Acetaldehyde') ;
    add_line(model,'F1/1','CSTR/1') ; add_line(model,'Adjust/1','CSTR/2') ;
    add_line(model,'CSTR/1','Adjust/1') ; add_line(model,'CSTR/1','Product/1') ;
end

function buildEx25(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 180 140 230],'Role','Feed') ;
    addSystem(model,'Splitter','nirp.blocks.Splitter',[180 165 300 245], ...
        'Fractions','[0.5 0.5]') ;
    addSystem(model,'Branch 1','nirp.blocks.Stream',[340 90 470 140], ...
        'Role','Intermediate') ;
    addSystem(model,'Branch 2','nirp.blocks.Stream',[340 275 470 325], ...
        'Role','Intermediate') ;
    pfrArgs = {'GeometryMode','Volume','VSource','Input port','D','0.1', ...
        'DUnit','m','HeatMode','Isothermal'} ;
    addSystem(model,'PFR 1','nirp.blocks.PFR',[520 75 660 155],pfrArgs{:}) ;
    addSystem(model,'PFR 2','nirp.blocks.PFR',[520 260 660 340],pfrArgs{:}) ;
    addSystem(model,'PFR 1 outlet','nirp.blocks.Stream',[700 90 840 140], ...
        'Role','Intermediate') ;
    addSystem(model,'PFR 2 outlet','nirp.blocks.Stream',[700 275 840 325], ...
        'Role','Intermediate') ;
    addSystem(model,'Mixer','nirp.blocks.Mixer',[880 165 1000 245],'NumInputs','2') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[360 390 640 460], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.8','InitialValue','20','MinValue','5', ...
        'MaxValue','200','ParameterUnit','L','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[1050 180 1190 230], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'F1/1','Splitter/1') ;
    add_line(model,'Splitter/1','Branch 1/1') ; add_line(model,'Splitter/2','Branch 2/1') ;
    add_line(model,'Branch 1/1','PFR 1/1') ; add_line(model,'Branch 2/1','PFR 2/1') ;
    add_line(model,'Adjust/1','PFR 1/2') ; add_line(model,'Adjust/1','PFR 2/2') ;
    add_line(model,'PFR 1/1','PFR 1 outlet/1') ; add_line(model,'PFR 2/1','PFR 2 outlet/1') ;
    add_line(model,'PFR 1 outlet/1','Mixer/1') ; add_line(model,'PFR 2 outlet/1','Mixer/2') ;
    add_line(model,'Mixer/1','Adjust/1') ; add_line(model,'Mixer/1','Product/1') ;
end

function buildEx26(model)
    buildAdjustedPfr(model,'A',0.6,30,10,100,'L','Isothermal') ;
end

function buildEx27(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'CSTR 1','nirp.blocks.CSTR',[370 120 510 195], ...
        'VSource','Input port','HeatMode','Adiabatic') ;
    addSystem(model,'CSTR 1 outlet','nirp.blocks.Stream',[550 135 690 185], ...
        'Role','Intermediate') ;
    addSystem(model,'CSTR 2','nirp.blocks.CSTR',[730 120 870 195], ...
        'VSource','Input port','HeatMode','Adiabatic') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[220 270 500 340], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.8','InitialValue','1','MinValue','0.5', ...
        'MaxValue','5','ParameterUnit','m^3','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[930 135 1070 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'F1/1','CSTR 1/1') ; add_line(model,'Adjust/1','CSTR 1/2') ;
    add_line(model,'CSTR 1/1','CSTR 1 outlet/1') ;
    add_line(model,'CSTR 1 outlet/1','CSTR 2/1') ; add_line(model,'Adjust/1','CSTR 2/2') ;
    add_line(model,'CSTR 2/1','Adjust/1') ; add_line(model,'CSTR 2/1','Product/1') ;
end

function buildEx28(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[370 120 510 195], ...
        'VSource','Input port','HeatMode','Adiabatic') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[40 270 320 340], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.8','InitialValue','3','MinValue','1', ...
        'MaxValue','20','ParameterUnit','m^3','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[570 135 710 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'F1/1','CSTR/1') ; add_line(model,'Adjust/1','CSTR/2') ;
    add_line(model,'CSTR/1','Adjust/1') ; add_line(model,'CSTR/1','Product/1') ;
end

function buildEx29(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[200 115 350 205], ...
        'V','1.5','VUnit','m^3','HeatMode','Heat exchange', ...
        'InitialTGuess','1050','InitialTGuessUnit','K') ;
    addSystem(model,'Jacket','nirp.blocks.Jacket',[200 10 350 75], ...
        'U',num2str(35.85*4184/60,17),'UUnit','W/(m^2*K)', ...
        'A','1','AUnit','m^2','UtilityTin','25', ...
        'UtilityTinUnit',[char(176) 'C'],'UtilityTout','NaN') ;
    addSystem(model,'Product','nirp.blocks.Stream',[410 135 550 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'F1/1','CSTR/1') ;add_line(model,'Jacket/1','CSTR/2'); add_line(model,'CSTR/1','Product/1') ;
end

function buildEx30(model)
    % T-121: fast reversible equilibrium is solved by the CSTR fallback.
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[200 115 350 205], ...
        'V','1.6','VUnit','m^3','HeatMode','Heat exchange') ;
    addSystem(model,'Jacket','nirp.blocks.Jacket',[200 10 350 75], ...
        'U','10','UUnit','W/(m^2*K)','A','2','AUnit','m^2', ...
        'UtilityTin','17','UtilityTinUnit',[char(176) 'C'], ...
        'UtilityTout','NaN') ;
    addSystem(model,'Product','nirp.blocks.Stream',[410 135 550 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'F1/1','CSTR/1') ;add_line(model,'Jacket/1','CSTR/2'); add_line(model,'CSTR/1','Product/1') ;
end

function buildEx31(model)
    addSystem(model,'F1','nirp.blocks.Stream',[250 135 380 185], ...
        'Role','Feed','QSource','Input port') ;
    for i = 1:3
        x = 440+(i-1)*330 ;
        addSystem(model,sprintf('CSTR %d',i),'nirp.blocks.CSTR',[x 120 x+140 195], ...
            'V','4.406197','VUnit','L','HeatMode','Isothermal') ;
        if i < 3
            addSystem(model,sprintf('CSTR %d outlet',i),'nirp.blocks.Stream', ...
                [x+175 135 x+315 185],'Role','Intermediate') ;
        end
    end
    addSystem(model,'Adjust','nirp.blocks.Adjust',[20 270 300 340], ...
        'TargetVariable','Component concentration','KeyComponent','A', ...
        'TargetValue','0.2','TargetUnit','mol/L','InitialValue','1.5','MinValue','1', ...
        'MaxValue','5','ParameterUnit','L/min','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[1430 135 1570 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'Adjust/1','F1/1') ; add_line(model,'F1/1','CSTR 1/1') ;
    add_line(model,'CSTR 1/1','CSTR 1 outlet/1') ;
    add_line(model,'CSTR 1 outlet/1','CSTR 2/1') ;
    add_line(model,'CSTR 2/1','CSTR 2 outlet/1') ;
    add_line(model,'CSTR 2 outlet/1','CSTR 3/1') ;
    add_line(model,'CSTR 3/1','Adjust/1') ; add_line(model,'CSTR 3/1','Product/1') ;
end

function buildEx32(model)
    buildProblem43(model,'PFR','CSTR') ;
end

function buildEx33(model)
    buildProblem43(model,'CSTR','PFR') ;
end

function buildProblem43(model,firstType,secondType)
    addSystem(model,'F1','nirp.blocks.Stream',[250 135 380 185], ...
        'Role','Feed','QSource','Input port') ;
    addProblem43Reactor(model,[firstType ' 1'],firstType,[440 115 590 205]) ;
    addSystem(model,'Intermediate','nirp.blocks.Stream',[640 135 780 185], ...
        'Role','Intermediate') ;
    addProblem43Reactor(model,[secondType ' 2'],secondType,[830 115 980 205]) ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[20 270 300 340], ...
        'TargetVariable','Component concentration','KeyComponent','A', ...
        'TargetValue','0.04','TargetUnit','mol/L','InitialValue','200','MinValue','100', ...
        'MaxValue','1000','ParameterUnit','m^3/h','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[1040 135 1180 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'Adjust/1','F1/1') ; add_line(model,'F1/1',[firstType ' 1/1']) ;
    add_line(model,[firstType ' 1/1'],'Intermediate/1') ;
    add_line(model,'Intermediate/1',[secondType ' 2/1']) ;
    add_line(model,[secondType ' 2/1'],'Adjust/1') ;
    add_line(model,[secondType ' 2/1'],'Product/1') ;
end

function addProblem43Reactor(model,name,type,position)
    if strcmp(type,'PFR')
        addSystem(model,name,'nirp.blocks.PFR',position,'GeometryMode','Volume', ...
            'V','0.666667','VUnit','m^3','D','0.5','DUnit','m', ...
            'HeatMode','Isothermal') ;
    else
        addSystem(model,name,'nirp.blocks.CSTR',position,'V','6.666667', ...
            'VUnit','m^3','HeatMode','Isothermal') ;
    end
end

function buildEx34(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'CSTR 1','nirp.blocks.CSTR',[190 115 340 205], ...
        'V','250.480335','VUnit','L','HeatMode','Isothermal') ;
    addSystem(model,'CSTR 1 outlet','nirp.blocks.Stream',[380 135 520 185], ...
        'Role','Intermediate') ;
    reactorArgs = {'V','250.480335','VUnit','L','HeatMode','Heat exchange'} ;
    addSystem(model,'CSTR 2','nirp.blocks.CSTR',[760 115 910 205],reactorArgs{:}) ;
    addSystem(model,'Jacket 2','nirp.blocks.Jacket',[760 10 910 75], ...
        'U','1180','UUnit','W/(m^2*K)','ASource','Input port', ...
        'UtilityTin','20','UtilityTinUnit',[char(176) 'C'],'UtilityTout','NaN') ;
    addSystem(model,'CSTR 2 outlet','nirp.blocks.Stream',[950 135 1090 185], ...
        'Role','Intermediate') ;
    addSystem(model,'CSTR 3','nirp.blocks.CSTR',[1330 115 1480 205],reactorArgs{:}) ;
    addSystem(model,'Jacket 3','nirp.blocks.Jacket',[1330 10 1480 75], ...
        'U','1180','UUnit','W/(m^2*K)','ASource','Input port', ...
        'UtilityTin','20','UtilityTinUnit',[char(176) 'C'],'UtilityTout','NaN') ;
    addSystem(model,'Adjust 2','nirp.blocks.Adjust',[540 280 820 350], ...
        'TargetVariable','Temperature','TargetValue','95', ...
        'TargetUnit',[char(176) 'C'],'InitialValue','0.1','MinValue','0.01', ...
        'MaxValue','1','ParameterUnit','m^2','Tolerance','1e-10') ;
    addSystem(model,'Adjust 3','nirp.blocks.Adjust',[1110 280 1390 350], ...
        'TargetVariable','Temperature','TargetValue','95', ...
        'TargetUnit',[char(176) 'C'],'InitialValue','0.1','MinValue','0.01', ...
        'MaxValue','1','ParameterUnit','m^2','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[1540 135 1680 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'F1/1','CSTR 1/1') ; add_line(model,'CSTR 1/1','CSTR 1 outlet/1') ;
    add_line(model,'CSTR 1 outlet/1','CSTR 2/1') ; add_line(model,'Adjust 2/1','Jacket 2/1');add_line(model,'Jacket 2/1','CSTR 2/2') ;
    add_line(model,'CSTR 2/1','Adjust 2/1') ; add_line(model,'CSTR 2/1','CSTR 2 outlet/1') ;
    add_line(model,'CSTR 2 outlet/1','CSTR 3/1') ; add_line(model,'Adjust 3/1','Jacket 3/1');add_line(model,'Jacket 3/1','CSTR 3/2') ;
    add_line(model,'CSTR 3/1','Adjust 3/1') ; add_line(model,'CSTR 3/1','Product/1') ;
end

function buildEx35(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[380 115 540 205], ...
        'V','1.2','VUnit','m^3','HeatMode','Heat exchange') ;
    addSystem(model,'Jacket','nirp.blocks.Jacket',[380 10 540 75], ...
        'U',num2str(15070e3/3600,17),'UUnit','W/(m^2*K)', ...
        'A','6','AUnit','m^2','UtilityTinSource','Input port','UtilityTout','NaN', ...
        'Condenses','on','LatentHeat', ...
        num2str((606.5-0.695*(401.4397-273.15))*4184,17)) ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[40 270 320 340], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.6','InitialValue','420','MinValue','380', ...
        'MaxValue','480','ParameterUnit','K','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[600 135 740 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'F1/1','CSTR/1') ; add_line(model,'Adjust/1','Jacket/1');add_line(model,'Jacket/1','CSTR/2') ;
    add_line(model,'CSTR/1','Adjust/1') ; add_line(model,'CSTR/1','Product/1') ;
end

function buildEx36(model)
    addSystem(model,'Feed A','nirp.blocks.Stream',[20 80 140 130],'Role','Feed') ;
    addSystem(model,'Feed B','nirp.blocks.Stream',[20 230 140 280],'Role','Feed') ;
    addSystem(model,'Mixer','nirp.blocks.Mixer',[190 135 310 225],'NumInputs','2') ;
    addSystem(model,'Mixed feed','nirp.blocks.Stream',[350 155 490 205], ...
        'Role','Intermediate') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[720 135 880 225], ...
        'V','385','VUnit','L','HeatMode','Heat exchange') ;
    addSystem(model,'Jacket','nirp.blocks.Jacket',[720 30 880 95], ...
        'U','1200','UUnit','W/(m^2*K)','ASource','Input port','UtilityTin','18', ...
        'UtilityTinUnit',[char(176) 'C'],'UtilityTout','NaN') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[400 300 680 370], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','Feed A', ...
        'TargetValue','0.85','InitialValue','5','MinValue','2', ...
        'MaxValue','20','ParameterUnit','m^2','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[940 155 1080 205], ...
        'Role','Product','ReferenceFeed','Feed A','KeyComponent','A') ;
    add_line(model,'Feed A/1','Mixer/1') ; add_line(model,'Feed B/1','Mixer/2') ;
    add_line(model,'Mixer/1','Mixed feed/1') ; add_line(model,'Mixed feed/1','CSTR/1') ;
    add_line(model,'Adjust/1','Jacket/1') ;add_line(model,'Jacket/1','CSTR/2'); add_line(model,'CSTR/1','Adjust/1') ;
    add_line(model,'CSTR/1','Product/1') ;
end

function buildEx37(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'PFR','nirp.blocks.PFR',[370 115 520 205], ...
        'GeometryMode','Volume','VSource','Input port','D','0.1', ...
        'DUnit','m','HeatMode','Adiabatic') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[40 270 320 340], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.736641551419','InitialValue','100','MinValue','10', ...
        'MaxValue','1000','ParameterUnit','L','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[580 135 720 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'F1/1','PFR/1') ; add_line(model,'Adjust/1','PFR/2') ;
    add_line(model,'PFR/1','Adjust/1') ; add_line(model,'PFR/1','Product/1') ;
end

function buildEx38(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[370 115 520 205], ...
        'VSource','Input port','HeatMode','Isothermal') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[40 270 320 340], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.85','InitialValue','0.3','MinValue','0.1', ...
        'MaxValue','1','ParameterUnit','m^3','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[580 135 720 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'F1/1','CSTR/1') ; add_line(model,'Adjust/1','CSTR/2') ;
    add_line(model,'CSTR/1','Adjust/1') ; add_line(model,'CSTR/1','Product/1') ;
end

function buildEx39(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[370 115 530 205], ...
        'V','405.965302','VUnit','L','HeatMode','Heat exchange') ;
    addSystem(model,'Jacket','nirp.blocks.Jacket',[370 10 530 75], ...
        'U','175','UUnit','W/(m^2*K)','ASource','Input port', ...
        'UtilityTin','293.15','UtilityTinUnit','K', ...
        'UtilityTout','297.15','UtilityToutUnit','K','UtilityCp','4184') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[40 270 320 340], ...
        'TargetVariable','Temperature','TargetValue','313.15','TargetUnit','K', ...
        'InitialValue','1','MinValue','0.5','MaxValue','10', ...
        'ParameterUnit','m^2','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[590 135 730 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'F1/1','CSTR/1') ; add_line(model,'Adjust/1','Jacket/1');add_line(model,'Jacket/1','CSTR/2') ;
    add_line(model,'CSTR/1','Adjust/1') ; add_line(model,'CSTR/1','Product/1') ;
end

function buildEx40(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 210 140 260],'Role','Feed') ;
    guesses = [300 343 446] ; productNames = {'Product low','Product middle','Product high'} ;
    for i = 1:3
        y = 60+(i-1)*150 ;
        addSystem(model,sprintf('CSTR %d',i),'nirp.blocks.CSTR', ...
            [210 y 370 y+80],'V','18','VUnit','L','HeatMode','Adiabatic', ...
            'InitialTGuess',num2str(guesses(i)), 'InitialTGuessUnit','K') ;
        addSystem(model,productNames{i},'nirp.blocks.Stream', ...
            [440 y+15 590 y+65],'Role','Product', ...
            'ReferenceFeed','F1','KeyComponent','A') ;
        add_line(model,'F1/1',sprintf('CSTR %d/1',i)) ;
        add_line(model,sprintf('CSTR %d/1',i),[productNames{i} '/1']) ;
    end
end

function buildEx41(model)
    % Problem 48 (T-131, D-057): a Heater brings the feed from 25 C to the
    % operating temperature and the CSTR is isothermal; the heat of part b)
    % is the Heater duty plus the CSTR duty.
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'Heater','nirp.blocks.Heater',[190 120 340 200], ...
        'Mode','Outlet T','Tout','404.1','ToutUnit','K') ;
    addSystem(model,'Heater outlet','nirp.blocks.Stream',[390 135 530 185], ...
        'Role','Intermediate') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[600 115 750 205], ...
        'VSource','Input port','HeatMode','Isothermal') ;
    addSystem(model,'Adjust CSTR','nirp.blocks.Adjust',[530 270 810 340], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.2','InitialValue','50','MinValue','10', ...
        'MaxValue','500','ParameterUnit','L','Tolerance','1e-10') ;
    addSystem(model,'CSTR outlet','nirp.blocks.Stream',[810 135 950 185], ...
        'Role','Intermediate') ;
    addSystem(model,'PFR','nirp.blocks.PFR',[1110 115 1260 205], ...
        'GeometryMode','Volume','VSource','Input port','D','0.1', ...
        'DUnit','m','HeatMode','Adiabatic') ;
    addSystem(model,'Adjust PFR','nirp.blocks.Adjust',[1040 270 1320 340], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.25','InitialValue','30','MinValue','5', ...
        'MaxValue','500','ParameterUnit','L','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[1340 135 1480 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'F1/1','Heater/1') ; add_line(model,'Heater/1','Heater outlet/1') ;
    add_line(model,'Heater outlet/1','CSTR/1') ; add_line(model,'Adjust CSTR/1','CSTR/2') ;
    add_line(model,'CSTR/1','Adjust CSTR/1') ;
    add_line(model,'CSTR/1','CSTR outlet/1') ; add_line(model,'CSTR outlet/1','PFR/1') ;
    add_line(model,'Adjust PFR/1','PFR/2') ; add_line(model,'PFR/1','Adjust PFR/1') ;
    add_line(model,'PFR/1','Product/1') ;
end

function buildEx42(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[370 115 530 205], ...
        'V','1.6','VUnit','m^3','HeatMode','Heat exchange', ...
        'InitialTGuess','528.8','InitialTGuessUnit','K') ;
    addSystem(model,'Jacket','nirp.blocks.Jacket',[370 10 530 75], ...
        'U','10','UUnit','W/(m^2*K)','ASource','Input port', ...
        'UtilityTin','17','UtilityTinUnit',[char(176) 'C'], ...
        'UtilityTout','NaN') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[40 270 320 340], ...
        'TargetVariable','Temperature','TargetValue','528.8','TargetUnit','K', ...
        'InitialValue','90','MinValue','50','MaxValue','150', ...
        'ParameterUnit','m^2','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[590 135 730 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    add_line(model,'F1/1','CSTR/1') ; add_line(model,'Adjust/1','Jacket/1');add_line(model,'Jacket/1','CSTR/2') ;
    add_line(model,'CSTR/1','Adjust/1') ; add_line(model,'CSTR/1','Product/1') ;
end

function buildEx43(model)
    % Problem 15: tubes of 3.5 m x 20 cm in series; the Adjust finds the
    % total volume for X = 0.6 and the number of tubes is V/V_tube.
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'PFR','nirp.blocks.PFR',[370 115 520 205], ...
        'GeometryMode','Volume','VSource','Input port','D','0.2', ...
        'DUnit','m','HeatMode','Isothermal') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[40 270 320 340], ...
        'TargetVariable','Conversion','KeyComponent','C2H2','ReferenceFeed','F1', ...
        'TargetValue','0.6','InitialValue','1','MinValue','0.1', ...
        'MaxValue','10','ParameterUnit','m^3','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[580 135 720 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','C2H2') ;
    add_line(model,'F1/1','PFR/1') ; add_line(model,'Adjust/1','PFR/2') ;
    add_line(model,'PFR/1','Adjust/1') ; add_line(model,'PFR/1','Product/1') ;
end

function buildEx44(model)
    % Problem 22: adiabatic PFR volume for NO2/NO = 5 at the outlet,
    % equivalent to X_NO = 44/54 with the stated feed.
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'PFR','nirp.blocks.PFR',[370 115 520 205], ...
        'GeometryMode','Volume','VSource','Input port','D','1', ...
        'DUnit','m','HeatMode','Adiabatic') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[40 270 320 340], ...
        'TargetVariable','Conversion','KeyComponent','NO','ReferenceFeed','F1', ...
        'TargetValue',num2str(44/54,17),'InitialValue','100','MinValue','10', ...
        'MaxValue','1000','ParameterUnit','m^3','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[580 135 720 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','NO') ;
    add_line(model,'F1/1','PFR/1') ; add_line(model,'Adjust/1','PFR/2') ;
    add_line(model,'PFR/1','Adjust/1') ; add_line(model,'PFR/1','Product/1') ;
end

function buildEx45(model)
    % Two identical feeds keep the adjusted and fixed-volume calculations
    % independent while presenting both requested results in one flowsheet.
    addSystem(model,'F1','nirp.blocks.Stream',[20 90 140 140],'Role','Feed') ;
    addSystem(model,'PFR adjusted','nirp.blocks.PFR',[370 70 530 160], ...
        'GeometryMode','Volume','VSource','Input port','D','1', ...
        'DUnit','m','HeatMode','Isothermal') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[40 250 320 320], ...
        'TargetVariable','Conversion','KeyComponent','A','ReferenceFeed','F1', ...
        'TargetValue','0.8','InitialValue','50000','MinValue','10000', ...
        'MaxValue','150000','ParameterUnit','L','Tolerance','1e-10') ;
    addSystem(model,'Product adjusted','nirp.blocks.Stream',[600 90 760 140], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','A') ;
    addSystem(model,'F2','nirp.blocks.Stream',[20 390 140 440],'Role','Feed') ;
    addSystem(model,'PFR 50000 L','nirp.blocks.PFR',[370 370 530 460], ...
        'GeometryMode','Volume','V','50000','VUnit','L','D','1', ...
        'DUnit','m','HeatMode','Isothermal') ;
    addSystem(model,'Product 50000 L','nirp.blocks.Stream',[600 390 760 440], ...
        'Role','Product','ReferenceFeed','F2','KeyComponent','A') ;
    add_line(model,'F1/1','PFR adjusted/1') ;
    add_line(model,'Adjust/1','PFR adjusted/2') ;
    add_line(model,'PFR adjusted/1','Adjust/1') ;
    add_line(model,'PFR adjusted/1','Product adjusted/1') ;
    add_line(model,'F2/1','PFR 50000 L/1') ;
    add_line(model,'PFR 50000 L/1','Product 50000 L/1') ;
end

function buildEx46(model)
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[250 115 410 205], ...
        'V','200','VUnit','L','HeatMode','Isothermal') ;
    addSystem(model,'Product','nirp.blocks.Stream',[480 135 620 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','NO') ;
    add_line(model,'F1/1','CSTR/1') ; add_line(model,'CSTR/1','Product/1') ;
end

function buildEx47(model)
    addSystem(model,'F1','nirp.blocks.Stream',[250 120 380 170], ...
        'Role','Feed','TSource','Input port') ;
    addSystem(model,'CSTR','nirp.blocks.CSTR',[440 105 600 195], ...
        'V','200','VUnit','L','HeatMode','Adiabatic','InitialTGuess','500', ...
        'InitialTGuessUnit','K') ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[20 250 300 320], ...
        'TargetVariable','Temperature','TargetValue','500','TargetUnit','K', ...
        'InitialValue','300','MinValue','250','MaxValue','400', ...
        'ParameterUnit','K','Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[670 120 810 170], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent','NO') ;
    add_line(model,'Adjust/1','F1/1') ; add_line(model,'F1/1','CSTR/1') ;
    add_line(model,'CSTR/1','Adjust/1') ; add_line(model,'CSTR/1','Product/1') ;
end

function buildAdjustedPfr(model,keyComponent,target,initialValue,minimum,maximum,unit,heatMode)
    addSystem(model,'F1','nirp.blocks.Stream',[20 135 140 185],'Role','Feed') ;
    addSystem(model,'PFR','nirp.blocks.PFR',[370 115 510 205], ...
        'GeometryMode','Volume','VSource','Input port','D','0.1', ...
        'DUnit','m','HeatMode',heatMode) ;
    addSystem(model,'Adjust','nirp.blocks.Adjust',[40 270 320 340], ...
        'TargetVariable','Conversion','KeyComponent',keyComponent, ...
        'ReferenceFeed','F1','TargetValue',num2str(target,17), ...
        'InitialValue',num2str(initialValue,17),'MinValue',num2str(minimum,17), ...
        'MaxValue',num2str(maximum,17),'ParameterUnit',unit,'Tolerance','1e-10') ;
    addSystem(model,'Product','nirp.blocks.Stream',[570 135 710 185], ...
        'Role','Product','ReferenceFeed','F1','KeyComponent',keyComponent) ;
    add_line(model,'F1/1','PFR/1') ; add_line(model,'Adjust/1','PFR/2') ;
    add_line(model,'PFR/1','Adjust/1') ; add_line(model,'PFR/1','Product/1') ;
end

function routeSignalLines(model)
    % Orthogonal routes for Adjust feedback and Jacket signal lines.
    blocks=[find_system(model,'SearchDepth',1,'BlockType','MATLABSystem','System','nirp.blocks.Adjust'); ...
        find_system(model,'SearchDepth',1,'BlockType','MATLABSystem','System','nirp.blocks.Jacket')];
    lines=[];
    for i=1:numel(blocks)
        handles=get_param(blocks{i},'LineHandles');
        lines=[lines handles.Inport(:)' handles.Outport(:)']; %#ok<AGROW>
    end
    lines=unique(lines(lines~=-1));
    if ~isempty(lines),Simulink.BlockDiagram.routeLine(lines);end
end

function addSystem(model,name,className,position,varargin)
    minimumWidth=0;
    switch className
        case 'nirp.blocks.Stream',minimumWidth=120;
        case 'nirp.blocks.Heater',minimumWidth=150;
        case 'nirp.blocks.Jacket',minimumWidth=150;
        case 'nirp.blocks.Recycle',minimumWidth=180;
        case 'nirp.blocks.Adjust',minimumWidth=280;
    end
    position(3)=max(position(3),position(1)+minimumWidth);
    if strcmp(className,'nirp.blocks.Adjust')
        % T-131: the Adjust faces left (input on the right, output on the
        % left) so the measured line does not cross the reactor.
        varargin=[{'Orientation','left'} varargin];
    end
    add_block('simulink/User-Defined Functions/MATLAB System',[model '/' name], ...
        'System',className,'Position',position,varargin{:});
    if ~strcmp(className,'nirp.blocks.Stream')
        nirp.flowsheet.setupUnitBlock([model '/' name]);
    end
end
