% run_validation - Validate collection-problem flowsheets against scripts.
% =========================================================================
% Javier Berenguer Sabater
% Created: October 3, 2026. Last update: October 7, 2026
% =========================================================================

repoRoot = fileparts(fileparts(mfilename('fullpath'))) ; addpath(repoRoot) ;
validationFolder = tempname ; mkdir(validationFolder) ; addpath(validationFolder) ;
fileGenerationConfig = Simulink.fileGenControl('getConfig') ;
generatedFolder = tempname ; mkdir(generatedFolder) ;
Simulink.fileGenControl('set','CacheFolder',fullfile(generatedFolder,'cache'), ...
    'CodeGenFolder',fullfile(generatedFolder,'codegen'),'createDir',true) ;
validationCleanup = onCleanup(@() restoreValidationEnvironment( ...
    fileGenerationConfig,generatedFolder,validationFolder)) ;
files = build_examples(validationFolder) ;

pkg37 = nirp.pkg.examples.problem37Liquid() ;
rs37 = nirp.pkg.toReactionSys(pkg37) ;
feedA = nirp.pkg.feedStream(pkg37,"Feed A") ;
feedB = nirp.pkg.feedStream(pkg37,"Feed B") ;
mixed37 = nirp.units.mixer([],{feedA,feedB},rs37) ;
first37 = nirp.units.cstr(struct('V',0.2),mixed37,rs37) ;
out37 = nirp.units.cstr(struct('V',0.2),first37,rs37) ;
diagram37 = simulateValidationExample(files(8),"ex8_problem37a_series") ;

pkg40 = nirp.pkg.examples.problem40Gas() ;
rs40 = nirp.pkg.toReactionSys(pkg40) ; feed40 = nirp.pkg.feedStream(pkg40,"F1") ;
first40a = nirp.units.cstr(struct('V',0.4),feed40,rs40) ;
out40a = nirp.units.cstr(struct('V',0.4),first40a,rs40) ;
diagram40a = simulateValidationExample(files(9),"ex9_problem40a_series") ;
branches40b = nirp.units.splitter(struct('fractions',[0.5 0.5]),feed40,rs40) ;
branch1 = nirp.units.cstr(struct('V',0.4),branches40b{1},rs40) ;
branch2 = nirp.units.cstr(struct('V',0.4),branches40b{2},rs40) ;
out40b = nirp.units.mixer([],{branch1,branch2},rs40) ;
diagram40b = simulateValidationExample(files(4),"ex4_problem40b_parallel") ;

pkg42 = nirp.pkg.examples.problem42SecondOrder() ;
rs42 = nirp.pkg.toReactionSys(pkg42) ; feed42 = nirp.pkg.feedStream(pkg42,"F1") ;
first42cp = nirp.units.cstr(struct('V',1),feed42,rs42) ;
out42cp = nirp.units.pfr(struct('V',1,'D',0.1),first42cp,rs42) ;
diagram42cp = simulateValidationExample(files(10),"ex10_problem42_cstr_pfr") ;
first42pc = nirp.units.pfr(struct('V',1,'D',0.1),feed42,rs42) ;
out42pc = nirp.units.cstr(struct('V',1),first42pc,rs42) ;
diagram42pc = simulateValidationExample(files(11),"ex11_problem42_pfr_cstr") ;

pkg19 = nirp.pkg.examples.problem19Gas() ;
rs19 = nirp.pkg.toReactionSys(pkg19) ; feed19 = nirp.pkg.feedStream(pkg19,"F1") ;
out19 = nirp.units.pfr(struct('V',1.5,'D',0.1,'heatMode','Adiabatic'), ...
    feed19,rs19) ;
diagram19 = simulateValidationExample(files(12),"ex12_problem19_adiabatic_pfr") ;

pkg44 = nirp.pkg.readDictionary(replace(files(7),".slx",".sldd")) ;
rs44 = nirp.pkg.toReactionSys(pkg44) ; feed44 = nirp.pkg.feedStream(pkg44,"F1") ;
out44single = nirp.units.cstr(struct('V',0.5,'heatMode','Adiabatic', ...
    'initialTemperatureGuess',495),feed44,rs44) ;
first44 = nirp.units.cstr(struct('V',0.25,'heatMode','Adiabatic', ...
    'initialTemperatureGuess',490),feed44,rs44) ;
out44series = nirp.units.cstr(struct('V',0.25,'heatMode','Adiabatic', ...
    'initialTemperatureGuess',499),first44,rs44) ;
diagram44 = simulateValidationExample(files(7),"ex7_problem44c") ;

pkg21 = nirp.pkg.examples.problem21Gas() ;
rs21 = nirp.pkg.toReactionSys(pkg21) ; feed21 = nirp.pkg.feedStream(pkg21,"F1") ;
temperature21a = fzero(@(temperature) pfrConversionAtTemperature( ...
    temperature,feed21,rs21,'Isothermal')-0.9,[330 450]) ;
temperature21b = fzero(@(temperature) pfrConversionAtTemperature( ...
    temperature,feed21,rs21,'Adiabatic')-0.9,[380 520]) ;
diagram21a = simulateValidationExample(files(13), ...
    "ex13_problem21a_isothermal_pfr") ;
diagram21b = simulateValidationExample(files(14), ...
    "ex14_problem21b_adiabatic_pfr") ;

pkg27 = nirp.pkg.examples.problem27Jacketed() ;
rs27 = nirp.pkg.toReactionSys(pkg27) ; feed27 = nirp.pkg.feedStream(pkg27,"F1") ;
temperature27 = fzero(@(temperature) cstr27ConversionAtTemperature( ...
    temperature,feed27,rs27)-0.8,[285 305]) ;
diagram27 = simulateValidationExample(files(15), ...
    "ex15_problem27_jacketed_cstr") ;

pkg30 = nirp.pkg.examples.problem30Liquid() ;
rs30 = nirp.pkg.toReactionSys(pkg30) ;
feedPO = nirp.pkg.feedStream(pkg30,"Feed PO") ;
feedW = nirp.pkg.feedStream(pkg30,"Feed W") ;
mixed30 = nirp.units.mixer([],{feedPO,feedW},rs30) ;
out30 = nirp.units.cstr(struct('V',1.136,'heatMode','Adiabatic'),mixed30,rs30) ;
out31 = nirp.units.cstr(struct('V',1.136,'heatMode','Other', ...
    'U',567.7,'A',3.7,'utilityTin',302.65),mixed30,rs30) ;
diagram30 = simulateValidationExample(files(16), ...
    "ex16_problem30_adiabatic_cstr") ;
diagram31 = simulateValidationExample(files(17), ...
    "ex17_problem31_cooled_cstr") ;

pkg44a = nirp.pkg.examples.problem44Liquid() ;
rs44a = nirp.pkg.toReactionSys(pkg44a) ; feed44a = nirp.pkg.feedStream(pkg44a,"F1") ;
volume44pfr = fzero(@(volume) reactorConversion(feed44a, ...
    nirp.units.pfr(struct('V',volume,'D',0.1,'heatMode','Adiabatic'), ...
    feed44a,rs44a),1)-0.85,[0.005 0.1]) ;
volume44cstr = fzero(@(volume) reactorConversion(feed44a, ...
    nirp.units.cstr(struct('V',volume,'heatMode','Adiabatic'), ...
    feed44a,rs44a),1)-0.85,[0.01 0.03]) ;
diagram44a = simulateValidationExample(files(18),"ex18_problem44a_volumes") ;

pkg45 = nirp.pkg.examples.problem45Liquid() ;
rs45 = nirp.pkg.toReactionSys(pkg45) ; feed45 = nirp.pkg.feedStream(pkg45,"F1") ;
volume45 = fzero(@(volume) threeCstrConversion(volume,feed45,rs45)-0.9, ...
    [0.1 0.5]) ;
temperature45 = fzero(@(temperature) cstr45OutletTemperature( ...
    temperature,feed45,rs45)-368.15,[335 355]) ;
diagram45a = simulateValidationExample(files(19), ...
    "ex19_problem45a_three_cstrs") ;
diagram45b = simulateValidationExample(files(20), ...
    "ex20_problem45b_feed_temperature") ;

pkg17 = nirp.pkg.examples.problem17AdiabaticGas() ;
rs17 = nirp.pkg.toReactionSys(pkg17) ; feed17 = nirp.pkg.feedStream(pkg17,"F1") ;
volume17 = fzero(@(volume) pfrVolumeConversion( ...
    volume,feed17,rs17,'Adiabatic')-0.35,[0.001 0.1]) ;
diagram17 = simulateValidationExample(files(21), ...
    "ex21_problem17_adiabatic_pfr_volume") ;

pkg18 = nirp.pkg.examples.problem18AcetoneCracking() ;
rs18 = nirp.pkg.toReactionSys(pkg18) ; feed18 = nirp.pkg.feedStream(pkg18,"F1") ;
volume18 = fzero(@(volume) pfrVolumeConversion( ...
    volume,feed18,rs18,'Adiabatic')-0.2,[0.1 10]) ;
diagram18 = simulateValidationExample(files(22), ...
    "ex22_problem18_acetone_cracking") ;

pkg23 = nirp.pkg.examples.problem23ButaneIsomerization() ;
rs23 = nirp.pkg.toReactionSys(pkg23) ; feed23 = nirp.pkg.feedStream(pkg23,"F1") ;
volume23 = fzero(@(volume) pfrVolumeConversion( ...
    volume,feed23,rs23,'Adiabatic')-0.65,[0.2 5]) ;
diagram23 = simulateValidationExample(files(23), ...
    "ex23_problem23_butane_isomerization") ;

pkg26 = nirp.pkg.examples.problem26ScaleUpGas() ;
rs26 = nirp.pkg.toReactionSys(pkg26) ; feed26 = nirp.pkg.feedStream(pkg26,"F1") ;
volume26 = fzero(@(volume) cstrVolumeConversion( ...
    volume,feed26,rs26,'Isothermal')-0.75,[100 3000]) ;
diagram26 = simulateValidationExample(files(24), ...
    "ex24_problem26_scale_up_cstr") ;

pkg38 = nirp.pkg.examples.problem38ParallelGas() ;
rs38 = nirp.pkg.toReactionSys(pkg38) ; feed38 = nirp.pkg.feedStream(pkg38,"F1") ;
volume38 = fzero(@(volume) parallelPfrConversion(volume,feed38,rs38)-0.8, ...
    [0.005 0.2]) ;
diagram38 = simulateValidationExample(files(25), ...
    "ex25_problem38_parallel_pfrs") ;

pkg40c = nirp.pkg.examples.problem40cGas() ;
rs40c = nirp.pkg.toReactionSys(pkg40c) ; feed40c = nirp.pkg.feedStream(pkg40c,"F1") ;
volume40c = fzero(@(volume) pfrVolumeConversion( ...
    volume,feed40c,rs40c,'Isothermal')-0.6,[0.01 0.1]) ;
diagram40c = simulateValidationExample(files(26), ...
    "ex26_problem40c_pfr_volume") ;

pkg49 = nirp.pkg.examples.problem49AdiabaticLiquid() ;
rs49 = nirp.pkg.toReactionSys(pkg49) ; feed49 = nirp.pkg.feedStream(pkg49,"F1") ;
volume49a = fzero(@(volume) twoCstrConversion(volume,feed49,rs49)-0.8, ...
    [0.5 5]) ;
volume49b = fzero(@(volume) cstrVolumeConversion( ...
    volume,feed49,rs49,'Adiabatic')-0.8,[1 20]) ;
diagram49a = simulateValidationExample(files(27), ...
    "ex27_problem49a_two_adiabatic_cstrs") ;
diagram49b = simulateValidationExample(files(28), ...
    "ex28_problem49b_one_adiabatic_cstr") ;

pkg34 = nirp.pkg.examples.problem34dMonsanto() ;
rs34 = nirp.pkg.toReactionSys(pkg34) ; feed34 = nirp.pkg.feedStream(pkg34,"F1") ;
out34 = nirp.units.cstr(struct('V',1.5,'heatMode','Other', ...
    'U',35.85*4184/60,'A',1,'utilityTin',298.15, ...
    'initialTemperatureGuess',1050),feed34,rs34) ;
diagram34 = simulateValidationExample(files(29), ...
    "ex29_problem34d_jacketed_cstr") ;

% T-121: cooled, fast reversible gas CSTR (problem 33b).
pkg33 = nirp.pkg.examples.problem33Gas() ;
rs33 = nirp.pkg.toReactionSys(pkg33) ; feed33 = nirp.pkg.feedStream(pkg33,"F1") ;
out33 = nirp.units.cstr(struct('V',1.6,'heatMode','Other', ...
    'U',10,'A',2,'utilityTin',290.15),feed33,rs33) ;
diagram33 = simulateValidationExample(files(30), ...
    "ex30_problem33b_cooled_gas_cstr") ;

pkg41 = nirp.pkg.examples.problem41SecondOrder() ;
rs41 = nirp.pkg.toReactionSys(pkg41) ; feed41 = nirp.pkg.feedStream(pkg41,"F1") ;
volume41 = 4.406197e-3 ;
flow41 = fzero(@(flow) threeCstrConcentration(flow,volume41,feed41,rs41)-200, ...
    [1 5]*1e-3/60) ;
out41 = threeCstrAtFlow(flow41,volume41,feed41,rs41) ;
diagram41 = simulateValidationExample(files(31),"ex31_problem41_three_cstrs") ;

pkg43 = nirp.pkg.examples.problem43Liquid() ;
rs43 = nirp.pkg.toReactionSys(pkg43) ; feed43 = nirp.pkg.feedStream(pkg43,"F1") ;
flow43pc = fzero(@(flow) problem43Concentration(flow,feed43,rs43,true)-40, ...
    [100 1000]/3600) ;
flow43cp = fzero(@(flow) problem43Concentration(flow,feed43,rs43,false)-40, ...
    [100 1000]/3600) ;
out43pc = problem43AtFlow(flow43pc,feed43,rs43,true) ;
out43cp = problem43AtFlow(flow43cp,feed43,rs43,false) ;
diagram43pc = simulateValidationExample(files(32), ...
    "ex32_problem43_pfr_then_cstr") ;
diagram43cp = simulateValidationExample(files(33), ...
    "ex33_problem43_cstr_then_pfr") ;

params45 = struct('V',0.250480335,'heatMode','Specified T', ...
    'specifiedT',368.15) ;
out45first = nirp.units.cstr(params45,feed45,rs45) ;
area45second = fzero(@(area) cooled45Temperature(area,out45first,rs45)-368.15, ...
    [0.01 1]) ;
out45second = cooled45(area45second,out45first,rs45) ;
area45third = fzero(@(area) cooled45Temperature(area,out45second,rs45)-368.15, ...
    [0.01 1]) ;
out45third = cooled45(area45third,out45second,rs45) ;
diagram45c = simulateValidationExample(files(34), ...
    "ex34_problem45c_cooled_tanks") ;

pkg28 = nirp.pkg.examples.problem28SteamJacket() ;
rs28 = nirp.pkg.toReactionSys(pkg28) ; feed28 = nirp.pkg.feedStream(pkg28,"F1") ;
utility28 = fzero(@(temperature) steam28Conversion(temperature,feed28,rs28)-0.6, ...
    [380 480]) ;
[out28,info28] = steam28(utility28,feed28,rs28) ;
latentHeat28 = (606.5-0.695*(utility28-273.15))*4184 ;
steamFlow28 = info28.heatDuty/latentHeat28*60 ;
diagram28 = simulateValidationExample(files(35), ...
    "ex35_problem28_steam_jacket") ;
diagramSteam28 = diagnosticHeat(diagram28,"ex35_problem28_steam_jacket", ...
    "CSTR")/latentHeat28*60 ;

pkg36 = nirp.pkg.examples.problem36AirCooled() ;
rs36 = nirp.pkg.toReactionSys(pkg36) ;
feed36a = nirp.pkg.feedStream(pkg36,"Feed A") ;
feed36b = nirp.pkg.feedStream(pkg36,"Feed B") ;
mixed36 = nirp.units.mixer([],{feed36a,feed36b},rs36) ;
area36 = fzero(@(area) problem36Conversion(area,mixed36,feed36a,rs36)-0.85, ...
    [2 20]) ;
[out36,info36] = problem36(area36,mixed36,rs36) ;
diagram36 = simulateValidationExample(files(36), ...
    "ex36_problem36_air_cooled_cstr") ;

problem = ["P37a";"P37a";"P37a";"P40a";"P40b";"P42";"P42"; ...
    "P19";"P19";"P44c";"P44c";"P21a";"P21b";"P27"; ...
    "P30";"P30";"P31";"P31";"P44a";"P44a";"P45a";"P45b"; ...
    "P17";"P18";"P23";"P26";"P38";"P40c";"P49a";"P49b"; ...
    "P34d";"P34d";"P33b";"P33b"] ;
magnitude = ["C_A1 (mol/L)";"C_A2 (mol/L)";"X_A";"X_A";"X_A"; ...
    "X (CSTR+PFR)";"X (PFR+CSTR)";"X_A";"T_out (K)"; ...
    "X_A (one CSTR)";"X_A (two CSTRs)";"Adjusted T (K)"; ...
    "Adjusted T (K)";"Adjusted T (K)";"T_out (K)";"X_PO"; ...
    "T_out (K)";"X_PO";"Adjusted PFR V (L)";"Adjusted CSTR V (L)"; ...
    "Adjusted V per CSTR (L)";"Adjusted feed T (K)"; ...
    "Adjusted PFR V (L)";"Adjusted PFR V (m^3)"; ...
    "Adjusted PFR V (m^3)";"Adjusted CSTR V (m^3)"; ...
    "Adjusted V per PFR (L)";"Adjusted PFR V (L)"; ...
    "Adjusted V per CSTR (m^3)";"Adjusted CSTR V (m^3)"; ...
    "T_out (K)";"X_A";"T_out (K)";"X_A"] ;
diagram = [concentrationInMolPerL(diagram37.Streams.CSTR1Outlet.streamSI,1); ...
    concentrationInMolPerL(diagram37.Streams.Product.streamSI,1); ...
    diagram37.Streams.Product.conversion;diagram40a.Streams.Product.conversion; ...
    diagram40b.Streams.Product.conversion;diagram42cp.Streams.Product.conversion; ...
    diagram42pc.Streams.Product.conversion;diagram19.Streams.Product.conversion; ...
    diagram19.Streams.Product.streamSI.T;diagram44.Streams.Product500.conversion; ...
    diagram44.Streams.ProductSeries.conversion; ...
    diagram21a.Streams.F1.streamSI.T;diagram21b.Streams.F1.streamSI.T; ...
    diagram27.Streams.F1.streamSI.T;diagram30.Streams.Product.streamSI.T; ...
    diagram30.Streams.Product.conversion;diagram31.Streams.Product.streamSI.T; ...
    diagram31.Streams.Product.conversion; ...
    diagnosticVolume(diagram44a,"ex18_problem44a_volumes","PFR")*1000; ...
    diagnosticVolume(diagram44a,"ex18_problem44a_volumes","CSTR")*1000; ...
    diagnosticVolume(diagram45a,"ex19_problem45a_three_cstrs","CSTR 1")*1000; ...
    diagram45b.Streams.F1.streamSI.T; ...
    diagnosticVolume(diagram17,"ex21_problem17_adiabatic_pfr_volume","PFR")*1000; ...
    diagnosticVolume(diagram18,"ex22_problem18_acetone_cracking","PFR"); ...
    diagnosticVolume(diagram23,"ex23_problem23_butane_isomerization","PFR"); ...
    diagnosticVolume(diagram26,"ex24_problem26_scale_up_cstr","CSTR"); ...
    diagnosticVolume(diagram38,"ex25_problem38_parallel_pfrs","PFR 1")*1000; ...
    diagnosticVolume(diagram40c,"ex26_problem40c_pfr_volume","PFR")*1000; ...
    diagnosticVolume(diagram49a,"ex27_problem49a_two_adiabatic_cstrs","CSTR 1"); ...
    diagnosticVolume(diagram49b,"ex28_problem49b_one_adiabatic_cstr","CSTR"); ...
    diagram34.Streams.Product.streamSI.T;diagram34.Streams.Product.conversion; ...
    diagram33.Streams.Product.streamSI.T;diagram33.Streams.Product.conversion] ;
script = [concentrationInMolPerL(first37,1);concentrationInMolPerL(out37,1); ...
    conversion(feedA,out37,1);conversion(feed40,out40a,1); ...
    conversion(feed40,out40b,1);conversion(feed42,out42cp,1); ...
    conversion(feed42,out42pc,1);conversion(feed19,out19,1);out19.T; ...
    conversion(feed44,out44single,1);conversion(feed44,out44series,1); ...
    temperature21a;temperature21b;temperature27;out30.T; ...
    conversion(feedPO,out30,1);out31.T;conversion(feedPO,out31,1); ...
    volume44pfr*1000;volume44cstr*1000;volume45*1000;temperature45; ...
    volume17*1000;volume18;volume23;volume26;volume38*1000;volume40c*1000; ...
    volume49a;volume49b;out34.T;conversion(feed34,out34,1); ...
    out33.T;conversion(feed33,out33,1)] ;
official = [0.828;0.704;0.296;0.663;0.578;0.464;0.472;0.600; ...
    779.53;0.977;0.995;387;433;298.3;340.45;NaN;310.75;0.31; ...
    30.5;17.6;250.5;346.8;20.3;1.03;1.23;816.7;32.1;56.0; ...
    1.10;4.76;1067.95;0.371;772.6;0.869] ;
difference = abs(diagram-official) ;
note = strings(size(problem)) ;
note(problem == "P30" | problem == "P31") = ...
    "Known difference: graphical official solution" ;
note(problem == "P27") = ...
    "Hand check of the statement data gives 298.62 K (official 298.3 K)" ;
note(problem == "P34d" & magnitude == "T_out (K)") = ...
    "Known 0.5 K difference from the graphical official solution" ;
validation = table(problem,magnitude,diagram,script,official,difference,note, ...
    'VariableNames',{'Problem','Magnitude','Diagram','Script','Official', ...
    'Difference','Note'}) ;
disp(validation) ;
relative = abs(diagram-script)./max(abs(script),1e-15) ;
adjusted = ismember(problem,["P21a","P21b","P27","P44a","P45a","P45b", ...
    "P17","P18","P23","P26","P38","P40c","P49a","P49b"]) ;
assert(all(relative(~adjusted) <= 1e-9),'nirp:validation:mismatch', ...
    'A non-adjusted diagram differs from its script result by more than 1e-9.') ;
assert(all(relative(adjusted) <= 1e-5),'nirp:validation:adjustMismatch', ...
    'An adjusted parameter differs from its fzero result by more than 1e-5.') ;

problem124 = ["P41";"P41";"P43";"P43";"P43";"P43"; ...
    "P45c";"P45c";"P45c";"P45c";"P28";"P28";"P28"; ...
    "P36";"P36";"P36";"P36";"P36";"P36";"P36"] ;
magnitude124 = ["Adjusted Q (L/min)";"X_A"; ...
    "PFR+CSTR Q/Q0";"PFR+CSTR X_A";"CSTR+PFR Q/Q0";"CSTR+PFR X_A"; ...
    "Adjusted A2 (m^2)";"T2 (K)";"Adjusted A3 (m^2)";"T3 (K)"; ...
    "Steam T (K)";"Reactor T (K)";"Steam flow (kg/min)"; ...
    "Adjusted A (m^2)";"T (K)";"C_A (mol/L)";"C_B (mol/L)"; ...
    "C_R (mol/L)";"C_S (mol/L)";"Q (J/min)"] ;
concentration36 = nirp.stream.concentration(out36)/1000 ;
diagramConcentration36 = nirp.stream.concentration( ...
    diagram36.Streams.Product.streamSI)/1000 ;
diagram124 = [diagnosticParameter(diagram41,"ex31_problem41_three_cstrs","Adjust")*60000; ...
    streamConversion(diagram41.Streams.F1.streamSI,diagram41.Streams.Product.streamSI,1); ...
    diagnosticParameter(diagram43pc,"ex32_problem43_pfr_then_cstr","Adjust")*36; ...
    streamConversion(diagram43pc.Streams.F1.streamSI,diagram43pc.Streams.Product.streamSI,1); ...
    diagnosticParameter(diagram43cp,"ex33_problem43_cstr_then_pfr","Adjust")*36; ...
    streamConversion(diagram43cp.Streams.F1.streamSI,diagram43cp.Streams.Product.streamSI,1); ...
    diagnosticParameter(diagram45c,"ex34_problem45c_cooled_tanks","Adjust 2"); ...
    diagram45c.Streams.CSTR2Outlet.streamSI.T; ...
    diagnosticParameter(diagram45c,"ex34_problem45c_cooled_tanks","Adjust 3"); ...
    diagram45c.Streams.Product.streamSI.T; ...
    diagnosticParameter(diagram28,"ex35_problem28_steam_jacket","Adjust"); ...
    diagram28.Streams.Product.streamSI.T;diagramSteam28; ...
    diagnosticParameter(diagram36,"ex36_problem36_air_cooled_cstr","Adjust"); ...
    diagram36.Streams.Product.streamSI.T;diagramConcentration36(1:4); ...
    diagnosticHeat(diagram36,"ex36_problem36_air_cooled_cstr","CSTR")*60] ;
script124 = [flow41*60000;streamConversion(atFlow(feed41,flow41),out41,1); ...
    flow43pc/(100/3600);streamConversion(atFlow(feed43,flow43pc),out43pc,1); ...
    flow43cp/(100/3600);streamConversion(atFlow(feed43,flow43cp),out43cp,1); ...
    area45second;out45second.T;area45third;out45third.T;utility28;out28.T;steamFlow28; ...
    area36;out36.T;concentration36(1:4);info36.heatDuty*60] ;
% Published solutions (Q0 = 1 L/min in P41, so +95 % reads 1.95 L/min).
official124 = [1.95;0.8;3.88;0.96;1.84;0.96; ...
    0.195;368.15;0.091;368.15;401.3;399.6;1.16; ...
    9.43;298.6;1.50;7.25;2.54;5.96;-5.039e6] ;
difference124 = abs(diagram124-official124) ;
note124 = strings(size(problem124)) ;
note124(problem124=="P28" & magnitude124=="Steam T (K)") = ...
    "Known 0.14 K difference with the official solution" ;
note124(problem124=="P28" & magnitude124=="Reactor T (K)") = ...
    "Known 0.17 K difference with the official solution" ;
validation124 = table(problem124,magnitude124,diagram124,script124,official124, ...
    difference124,note124,'VariableNames',{'Problem','Magnitude','Diagram', ...
    'Script','Official','Difference','Note'}) ;
disp(validation124) ;
relative124 = abs(diagram124-script124)./max(abs(script124),1e-15) ;
adjusted124 = ismember(magnitude124,["Adjusted Q (L/min)","PFR+CSTR Q/Q0", ...
    "CSTR+PFR Q/Q0","Adjusted A2 (m^2)","Adjusted A3 (m^2)", ...
    "Steam T (K)","Adjusted A (m^2)"]) ;
assert(all(relative124(~adjusted124) <= 1e-9),'nirp:validation:mismatch124', ...
    'A T-124 diagram differs from its script result by more than 1e-9.') ;
assert(all(relative124(adjusted124) <= 1e-5),'nirp:validation:adjustMismatch124', ...
    'A T-124 adjusted parameter differs from its fzero result by more than 1e-5.') ;

pkg20 = nirp.pkg.examples.problem33Gas() ;
rs20 = nirp.pkg.toReactionSys(pkg20) ; feed20 = nirp.pkg.feedStream(pkg20,"F1") ;
[equilibrium20,equilibriumTemperature20] = problem20Equilibrium() ;
target20 = 0.85*equilibrium20 ;
volume20 = fzero(@(volume) streamConversion(feed20, ...
    nirp.units.pfr(struct('V',volume,'D',0.1,'heatMode','Adiabatic'), ...
    feed20,rs20),1)-target20,[0.01 1]) ;
diagram20 = simulateValidationExample(files(37), ...
    "ex37_problem20b_adiabatic_reversible_pfr") ;

pkg29 = nirp.pkg.examples.problem29Hydrolysis() ;
rs29 = nirp.pkg.toReactionSys(pkg29) ; feed29 = nirp.pkg.feedStream(pkg29,"F1") ;
volume29 = fzero(@(volume) cstrSpecifiedConversion( ...
    volume,313.15,feed29,rs29)-0.85,[0.1 1]) ;
[~,info29a] = nirp.units.cstr(struct('V',volume29, ...
    'heatMode','Specified T','specifiedT',313.15),feed29,rs29) ;
area29 = fzero(@(area) cstrHeatExchangeTemperature(area,volume29,175, ...
    293.15,297.15,feed29,rs29)-313.15,[0.5 10]) ;
water29 = -info29a.heatDuty/(4184*4) ;
diagram29a = simulateValidationExample(files(38),"ex38_problem29_cstr_volume") ;
diagram29b = simulateValidationExample(files(39),"ex39_problem29_cooling_area") ;

pkg32 = nirp.pkg.examples.problem32AdiabaticCstr() ;
rs32 = nirp.pkg.toReactionSys(pkg32) ; feed32 = nirp.pkg.feedStream(pkg32,"F1") ;
guesses32 = [300 343 446] ; out32 = cell(1,3) ;
for i = 1:3
    out32{i} = nirp.units.cstr(struct('V',18e-3,'heatMode','Adiabatic', ...
        'initialTemperatureGuess',guesses32(i)),feed32,rs32) ;
end
diagram32 = simulateValidationExample(files(40), ...
    "ex40_problem32_three_steady_states") ;

pkg48 = nirp.pkg.examples.problem48ReversibleGas() ;
rs48 = nirp.pkg.toReactionSys(pkg48) ; feed48 = nirp.pkg.feedStream(pkg48,"F1") ;
volume48c = fzero(@(volume) cstrSpecifiedConversion( ...
    volume,404.1,feed48,rs48)-0.2,[0.01 0.5]) ;
[out48c,info48c] = nirp.units.cstr(struct('V',volume48c, ...
    'heatMode','Specified T','specifiedT',404.1),feed48,rs48) ;
volume48p = fzero(@(volume) streamConversion(feed48, ...
    nirp.units.pfr(struct('V',volume,'D',0.1,'heatMode','Adiabatic'), ...
    out48c,rs48),1)-0.25,[0.005 0.5]) ;
area48 = info48c.heatDuty/(1200*(498.15-404.1)) ;
diagram48 = simulateValidationExample(files(41), ...
    "ex41_problem48_cstr_then_adiabatic_pfr") ;

[maximumT33,maximumX33] = problem33Maximum(feed20,rs20) ;
area33 = fzero(@(area) cstrHeatExchangeTemperature(area,1.6,10, ...
    290.15,NaN,feed20,rs20,528.8)-528.8,[50 150]) ;
diagram33d = simulateValidationExample(files(42), ...
    "ex42_problem33d_area_for_max_generation") ;

diagramVolume20 = diagnosticParameter(diagram20, ...
    "ex37_problem20b_adiabatic_reversible_pfr","Adjust") ;
out20AtDiagramParameter = nirp.units.pfr(struct('V',diagramVolume20, ...
    'D',0.1,'heatMode','Adiabatic'),feed20,rs20) ;
diagramVolume29 = diagnosticParameter(diagram29a, ...
    "ex38_problem29_cstr_volume","Adjust") ;
[~,info29AtDiagramParameter] = nirp.units.cstr(struct('V',diagramVolume29, ...
    'heatMode','Specified T','specifiedT',313.15),feed29,rs29) ;
diagramVolume48c = diagnosticParameter(diagram48, ...
    "ex41_problem48_cstr_then_adiabatic_pfr","Adjust CSTR") ;
diagramVolume48p = diagnosticParameter(diagram48, ...
    "ex41_problem48_cstr_then_adiabatic_pfr","Adjust PFR") ;
[out48cAtDiagramParameter,info48cAtDiagramParameter] = nirp.units.cstr( ...
    struct('V',diagramVolume48c,'heatMode','Specified T', ...
    'specifiedT',404.1),feed48,rs48) ;
out48pAtDiagramParameter = nirp.units.pfr(struct('V',diagramVolume48p, ...
    'D',0.1,'heatMode','Adiabatic'),out48cAtDiagramParameter,rs48) ;
diagramArea33 = diagnosticParameter(diagram33d, ...
    "ex42_problem33d_area_for_max_generation","Adjust") ;
out33AtDiagramParameter = nirp.units.cstr(struct('V',1.6, ...
    'heatMode','Other','U',10,'A',diagramArea33,'utilityTin',290.15, ...
    'initialTemperatureGuess',528.8),feed20,rs20) ;

problem125 = ["P20a";"P20a";"P20b";"P20b";"P29a";"P29a"; ...
    "P29b";"P29c";"P32a";"P32a";"P32a";"P32a";"P32a";"P32a"; ...
    "P48a";"P48b";"P48d";"P48d";"P48c";"P33c";"P33c";"P33d";"P33d"] ;
magnitude125 = ["Derived X_eq";"Derived T_eq (K)";"Adjusted PFR V (L)";"X_A"; ...
    "Adjusted CSTR V (L)";"Q (W)";"Adjusted A (m^2)";"Water flow (kg/s)"; ...
    "Low X_A";"Low T (K)";"Middle X_A";"Middle T (K)";"High X_A";"High T (K)"; ...
    "Adjusted CSTR V (L)";"Q (J/min)";"Adjusted PFR V (L)";"T_out (K)"; ...
    "Derived A (m^2)";"Derived maximum T (K)";"Derived X at maximum"; ...
    "Adjusted A (m^2)";"X_A"] ;
diagram125 = [equilibrium20;equilibriumTemperature20; ...
    diagnosticParameter(diagram20,"ex37_problem20b_adiabatic_reversible_pfr","Adjust")*1000; ...
    diagram20.Streams.Product.conversion; ...
    diagnosticParameter(diagram29a,"ex38_problem29_cstr_volume","Adjust")*1000; ...
    diagnosticHeat(diagram29a,"ex38_problem29_cstr_volume","CSTR"); ...
    diagnosticParameter(diagram29b,"ex39_problem29_cooling_area","Adjust");water29; ...
    diagram32.Streams.ProductLow.conversion;diagram32.Streams.ProductLow.streamSI.T; ...
    diagram32.Streams.ProductMiddle.conversion;diagram32.Streams.ProductMiddle.streamSI.T; ...
    diagram32.Streams.ProductHigh.conversion;diagram32.Streams.ProductHigh.streamSI.T; ...
    diagnosticParameter(diagram48,"ex41_problem48_cstr_then_adiabatic_pfr","Adjust CSTR")*1000; ...
    (diagnosticHeat(diagram48,"ex41_problem48_cstr_then_adiabatic_pfr","Heater")+ ...
    diagnosticHeat(diagram48,"ex41_problem48_cstr_then_adiabatic_pfr","CSTR"))*60; ...
    diagnosticParameter(diagram48,"ex41_problem48_cstr_then_adiabatic_pfr","Adjust PFR")*1000; ...
    diagram48.Streams.Product.streamSI.T;area48;maximumT33;maximumX33; ...
    diagnosticParameter(diagram33d,"ex42_problem33d_area_for_max_generation","Adjust"); ...
    diagram33d.Streams.Product.conversion] ;
script125 = [equilibrium20;equilibriumTemperature20;volume20*1000; ...
    streamConversion(feed20,out20AtDiagramParameter,1); ...
    volume29*1000;info29AtDiagramParameter.heatDuty;area29;water29; ...
    streamConversion(feed32,out32{1},1);out32{1}.T; ...
    streamConversion(feed32,out32{2},1);out32{2}.T; ...
    streamConversion(feed32,out32{3},1);out32{3}.T; ...
    volume48c*1000;info48cAtDiagramParameter.heatDuty*60;volume48p*1000; ...
    out48pAtDiagramParameter.T;area48;maximumT33;maximumX33;area33; ...
    streamConversion(feed20,out33AtDiagramParameter,1)] ;
% The published solution gives no heat duty for P29a, hence NaN.
official125 = [0.867;783.5;150;0.85*0.867;405.9;NaN;2.12;0.398; ...
    0.020;301.0;0.300;343.0;0.985;445.8;74.4;5.89e7;45.3;407.1; ...
    8.70;528.8;0.922;94.65;0.922] ;
difference125 = abs(diagram125-official125) ;
note125 = strings(size(problem125)) ;
note125(problem125=="P20b" & magnitude125=="Adjusted PFR V (L)") = ...
    "0.6% below official value, consistent with rounded X_eq" ;
note125(problem125=="P32a" & contains(magnitude125,"Middle")) = ...
    "Unstable steady state" ;
note125(problem125=="P48b") = "Heater duty + isothermal CSTR duty" ;
note125(problem125=="P48d" & magnitude125=="Adjusted PFR V (L)") = ...
    "0.9% below official value" ;
validation125 = table(problem125,magnitude125,diagram125,script125,official125, ...
    difference125,note125,'VariableNames',{'Problem','Magnitude','Diagram', ...
    'Script','Official','Difference','Note'}) ;
disp(validation125) ;
relative125 = abs(diagram125-script125)./max(abs(script125),1e-15) ;
adjusted125 = contains(magnitude125,"Adjusted") ;
assert(all(relative125(~adjusted125) <= 1e-9),'nirp:validation:mismatch125', ...
    'A non-adjusted T-125 row differs from its script result by more than 1e-9.') ;
assert(all(relative125(adjusted125) <= 1e-5),'nirp:validation:adjustMismatch125', ...
    'A T-125 adjusted parameter differs from its script result by more than 1e-5.') ;


% T-128: problem 15 (number of tubes) and problem 22 (NO oxidation).
pkg15 = nirp.pkg.examples.problem15Acetylene() ;
rs15 = nirp.pkg.toReactionSys(pkg15) ; feed15 = nirp.pkg.feedStream(pkg15,"F1") ;
pfr15 = @(volume) nirp.units.pfr(struct('V',volume,'D',0.2, ...
    'heatMode','Isothermal'),feed15,rs15) ;
volume15 = fzero(@(volume) streamConversion(feed15,pfr15(volume),1)-0.6, ...
    [0.1 10]) ;
tubeVolume15 = pi*0.1^2*3.5 ; % m^3, 3.5 m x 20 cm tube
diagram15 = simulateValidationExample(files(43),"ex43_problem15_number_of_tubes") ;
diagramVolume15 = diagnosticParameter(diagram15,"ex43_problem15_number_of_tubes","Adjust") ;
out15AtDiagramParameter = pfr15(diagramVolume15) ;

pkg22 = nirp.pkg.examples.problem22NOOxidation() ;
rs22 = nirp.pkg.toReactionSys(pkg22) ; feed22 = nirp.pkg.feedStream(pkg22,"F1") ;
pfr22 = @(volume) nirp.units.pfr(struct('V',volume,'D',1, ...
    'heatMode','Adiabatic'),feed22,rs22) ;
volume22 = fzero(@(volume) streamConversion(feed22,pfr22(volume),1)-44/54, ...
    [10 1000]) ;
diagram22 = simulateValidationExample(files(44),"ex44_problem22_no_oxidation") ;
diagramVolume22 = diagnosticParameter(diagram22,"ex44_problem22_no_oxidation","Adjust") ;
out22AtDiagramParameter = pfr22(diagramVolume22) ;
product22 = diagram22.Streams.Product.streamSI ;

problem128 = ["P15";"P15";"P15";"P15";"P22";"P22";"P22"] ;
magnitude128 = ["Adjusted PFR V (m^3)";"Derived tubes (V/V_tube)"; ...
    "X_A with 16 tubes";"X_A with 15 tubes";"Adjusted PFR V (m^3)"; ...
    "T_out (K)";"NO2/NO at outlet"] ;
diagram128 = [diagramVolume15;diagramVolume15/tubeVolume15; ...
    streamConversion(feed15,pfr15(16*tubeVolume15),1); ...
    streamConversion(feed15,pfr15(15*tubeVolume15),1); ...
    diagramVolume22;product22.T;product22.F(3)/product22.F(1)] ;
script128 = [volume15;volume15/tubeVolume15; ...
    streamConversion(feed15,pfr15(16*tubeVolume15),1); ...
    streamConversion(feed15,pfr15(15*tubeVolume15),1); ...
    volume22;out22AtDiagramParameter.T; ...
    out22AtDiagramParameter.F(3)/out22AtDiagramParameter.F(1)] ;
% Published: 16 tubes (P15) and 165 m^3 (P22); the rest is not published.
official128 = [NaN;16;NaN;NaN;165;NaN;5] ;
difference128 = abs(diagram128-official128) ;
note128 = strings(size(problem128)) ;
note128(magnitude128=="Derived tubes (V/V_tube)") = ...
    "15.92 tubes, rounded up to 16" ;
validation128 = table(problem128,magnitude128,diagram128,script128,official128, ...
    difference128,note128,'VariableNames',{'Problem','Magnitude','Diagram', ...
    'Script','Official','Difference','Note'}) ;
disp(validation128) ;
relative128 = abs(diagram128-script128)./max(abs(script128),1e-15) ;
adjusted128 = contains(magnitude128,"Adjusted") | ...
    magnitude128=="Derived tubes (V/V_tube)" ;
assert(all(relative128(~adjusted128) <= 1e-9),'nirp:validation:mismatch128', ...
    'A non-adjusted T-128 row differs from its script result by more than 1e-9.') ;
assert(all(relative128(adjusted128) <= 1e-5),'nirp:validation:adjustMismatch128', ...
    'A T-128 adjusted parameter differs from its fzero result by more than 1e-5.') ;
assert(abs(out22AtDiagramParameter.F(3)/out22AtDiagramParameter.F(1)-5) <= 1e-5, ...
    'nirp:validation:ratio128','P22 outlet NO2/NO ratio is not 5.') ;
function results = simulateValidationExample(file,name)
    evalin('base','clear nirpResults') ;
    load_system(char(file)) ; sim(char(name)) ;
    results = evalin('base','nirpResults') ;
    close_system(char(name),0) ; Simulink.data.dictionary.closeAll('-discard') ;
end

function value = concentrationInMolPerL(stream,index)
    concentrations = nirp.stream.concentration(stream) ;
    value = concentrations(index)/1000 ;
end

function value = conversion(feed,product,index)
    value = (feed.F(index)-product.F(index))/feed.F(index) ;
end

function value = streamConversion(feed,product,index)
    value = (feed.F(index)-product.F(index))/feed.F(index) ;
end

function stream = atFlow(reference,flow)
    stream = reference ;
    stream.F = reference.F*(flow/reference.Q) ; stream.Q = flow ;
    stream = nirp.stream.refresh(stream) ;
end

function product = threeCstrAtFlow(flow,volume,feed,rs)
    product = atFlow(feed,flow) ; params = struct('V',volume) ;
    for i = 1:3, product = nirp.units.cstr(params,product,rs) ; end
end

function value = threeCstrConcentration(flow,volume,feed,rs)
    product = threeCstrAtFlow(flow,volume,feed,rs) ;
    concentration = nirp.stream.concentration(product) ; value = concentration(1) ;
end

function product = problem43AtFlow(flow,feed,rs,pfrFirst)
    inlet = atFlow(feed,flow) ;
    pfr = @(stream) nirp.units.pfr(struct('V',0.666667,'D',0.5),stream,rs) ;
    cstr = @(stream) nirp.units.cstr(struct('V',6.666667),stream,rs) ;
    if pfrFirst, product = cstr(pfr(inlet)) ; else, product = pfr(cstr(inlet)) ; end
end

function value = problem43Concentration(flow,feed,rs,pfrFirst)
    product = problem43AtFlow(flow,feed,rs,pfrFirst) ;
    concentration = nirp.stream.concentration(product) ; value = concentration(1) ;
end

function product = cooled45(area,feed,rs)
    product = nirp.units.cstr(struct('V',0.250480335,'heatMode','Other', ...
        'U',1180,'A',area,'utilityTin',293.15),feed,rs) ;
end

function value = cooled45Temperature(area,feed,rs)
    product = cooled45(area,feed,rs) ; value = product.T ;
end

function [product,info] = steam28(temperature,feed,rs)
    [product,info] = nirp.units.cstr(struct('V',1.2,'heatMode','Other', ...
        'U',15070e3/3600,'A',6,'utilityTin',temperature),feed,rs) ;
end

function value = steam28Conversion(temperature,feed,rs)
    product = steam28(temperature,feed,rs) ; value = streamConversion(feed,product,1) ;
end

function [product,info] = problem36(area,feed,rs)
    [product,info] = nirp.units.cstr(struct('V',0.385,'heatMode','Other', ...
        'U',1200,'A',area,'utilityTin',291.15),feed,rs) ;
end

function value = problem36Conversion(area,feed,reference,rs)
    product = problem36(area,feed,rs) ; value = streamConversion(reference,product,1) ;
end

function [value,temperature] = problem20Equilibrium()
    adiabaticTemperature = @(conversionValue) 350.15+500*conversionValue ;
    equilibrium = @(conversionValue) (2*conversionValue)^2/(1-conversionValue)^2- ...
        (1.45e7/1.85e6)*exp(20000/(8.314*adiabaticTemperature(conversionValue))) ;
    value = fzero(equilibrium,[0.5 0.99]) ;
    temperature = adiabaticTemperature(value) ;
end

function value = cstrSpecifiedConversion(volume,temperature,feed,rs)
    product = nirp.units.cstr(struct('V',volume,'heatMode','Specified T', ...
        'specifiedT',temperature),feed,rs) ;
    value = streamConversion(feed,product,1) ;
end

function value = cstrHeatExchangeTemperature(area,volume,U,utilityTin, ...
        utilityTout,feed,rs,initialGuess)
    params = struct('V',volume,'heatMode','Other','U',U,'A',area, ...
        'utilityTin',utilityTin) ;
    if ~isnan(utilityTout), params.utilityTout = utilityTout ; end
    if nargin >= 9, params.initialTemperatureGuess = initialGuess ; end
    product = nirp.units.cstr(params,feed,rs) ; value = product.T ;
end

function [temperature,conversionValue] = problem33Maximum(feed,rs)
    objective = @(value) -cstrSpecifiedConversion(1.6,value,feed,rs) ;
    [temperature,negativeConversion] = fminbnd(objective,400,700, ...
        optimset('TolX',1e-10)) ;
    conversionValue = -negativeConversion ;
end

function value = diagnosticParameter(results,model,block)
    field = matlab.lang.makeValidName(model+"_"+block) ;
    value = results.Diagnostics.(field).lastInfo.value ;
end

function value = diagnosticHeat(results,model,block)
    field = matlab.lang.makeValidName(model+"_"+block) ;
    value = results.Diagnostics.(field).lastInfo.heatDuty ;
end

function value = reactorConversion(feed,product,index)
    value = conversion(feed,product,index) ;
end

function stream = atTemperature(stream,temperature)
    stream.T = temperature ;
    stream = nirp.stream.refresh(stream) ;
end

function value = pfrConversionAtTemperature(temperature,feed,rs,heatMode)
    inlet = atTemperature(feed,temperature) ;
    product = nirp.units.pfr(struct('V',1,'D',0.1, ...
        'heatMode',heatMode),inlet,rs) ;
    value = conversion(inlet,product,1) ;
end

function value = cstr27ConversionAtTemperature(temperature,feed,rs)
    inlet = atTemperature(feed,temperature) ;
    product = nirp.units.cstr(struct('V',0.2,'heatMode','Other', ...
        'U',300,'A',9,'utilityTin',273),inlet,rs) ;
    value = conversion(inlet,product,1) ;
end

function value = threeCstrConversion(volume,feed,rs)
    params = struct('V',volume,'heatMode','Specified T','specifiedT',368.15) ;
    first = nirp.units.cstr(params,feed,rs) ;
    second = nirp.units.cstr(params,first,rs) ;
    product = nirp.units.cstr(params,second,rs) ;
    value = conversion(feed,product,1) ;
end

function value = cstr45OutletTemperature(temperature,feed,rs)
    inlet = atTemperature(feed,temperature) ;
    product = nirp.units.cstr(struct('V',0.250480335, ...
        'heatMode','Adiabatic'),inlet,rs) ;
    value = product.T ;
end

function value = diagnosticVolume(results,model,block)
    field = matlab.lang.makeValidName(model+"_"+block) ;
    value = results.Diagnostics.(field).lastInfo.V ;
end

function value = pfrVolumeConversion(volume,feed,rs,heatMode)
    product = nirp.units.pfr(struct('V',volume,'D',0.1, ...
        'heatMode',heatMode),feed,rs) ;
    value = conversion(feed,product,1) ;
end

function value = cstrVolumeConversion(volume,feed,rs,heatMode)
    product = nirp.units.cstr(struct('V',volume,'heatMode',heatMode),feed,rs) ;
    value = conversion(feed,product,1) ;
end

function value = parallelPfrConversion(volume,feed,rs)
    branches = nirp.units.splitter(struct('fractions',[0.5 0.5]),feed,rs) ;
    first = nirp.units.pfr(struct('V',volume,'D',0.1),branches{1},rs) ;
    second = nirp.units.pfr(struct('V',volume,'D',0.1),branches{2},rs) ;
    product = nirp.units.mixer([],{first,second},rs) ;
    value = conversion(feed,product,1) ;
end

function value = twoCstrConversion(volume,feed,rs)
    params = struct('V',volume,'heatMode','Adiabatic') ;
    first = nirp.units.cstr(params,feed,rs) ;
    product = nirp.units.cstr(params,first,rs) ;
    value = conversion(feed,product,1) ;
end

function restoreValidationEnvironment(config,generatedFolder,validationFolder)
    bdclose('all') ; Simulink.data.dictionary.closeAll('-discard') ;
    Simulink.fileGenControl('setConfig','config',config) ;
    if contains([path pathsep],[validationFolder pathsep]), rmpath(validationFolder) ; end
    if isfolder(generatedFolder), rmdir(generatedFolder,'s') ; end
    if isfolder(validationFolder), rmdir(validationFolder,'s') ; end
end
