% run_validation - Validate collection-problem flowsheets against scripts.
% =========================================================================
% Javier Berenguer Sabater
% Created: October 3, 2026. Last update: October 3, 2026
% =========================================================================

repoRoot = fileparts(fileparts(mfilename('fullpath'))) ; addpath(repoRoot) ;
validationFolder = tempname ; mkdir(validationFolder) ; addpath(validationFolder) ;
fileGenerationConfig = Simulink.fileGenControl('getConfig') ;
generatedFolder = tempname ; mkdir(generatedFolder) ;
Simulink.fileGenControl('set','CacheFolder',fullfile(generatedFolder,'cache'), ...
    'CodeGenFolder',fullfile(generatedFolder,'codegen'),'createDir',true) ;
validationCleanup = onCleanup(@() restoreValidationEnvironment( ...
    fileGenerationConfig,generatedFolder,validationFolder)) ;
files = build_examples(validationFolder) ;

pkg37 = nirp.pkg.examples.problem37Liquid() ;
rs37 = nirp.pkg.toReactionSys(pkg37) ;
feedA = nirp.pkg.feedStream(pkg37,"Feed A") ;
feedB = nirp.pkg.feedStream(pkg37,"Feed B") ;
mixed37 = nirp.units.mixer([],{feedA,feedB},rs37) ;
first37 = nirp.units.cstr(struct('V',0.2),mixed37,rs37) ;
out37 = nirp.units.cstr(struct('V',0.2),first37,rs37) ;
diagram37 = simulateValidationExample(files(8),"ex8_problem37a_series") ;

pkg40 = nirp.pkg.examples.problem40Gas() ;
rs40 = nirp.pkg.toReactionSys(pkg40) ; feed40 = nirp.pkg.feedStream(pkg40,"F1") ;
first40a = nirp.units.cstr(struct('V',0.4),feed40,rs40) ;
out40a = nirp.units.cstr(struct('V',0.4),first40a,rs40) ;
diagram40a = simulateValidationExample(files(9),"ex9_problem40a_series") ;
branches40b = nirp.units.splitter(struct('fractions',[0.5 0.5]),feed40,rs40) ;
branch1 = nirp.units.cstr(struct('V',0.4),branches40b{1},rs40) ;
branch2 = nirp.units.cstr(struct('V',0.4),branches40b{2},rs40) ;
out40b = nirp.units.mixer([],{branch1,branch2},rs40) ;
diagram40b = simulateValidationExample(files(4),"ex4_problem40b_parallel") ;

pkg42 = nirp.pkg.examples.problem42SecondOrder() ;
rs42 = nirp.pkg.toReactionSys(pkg42) ; feed42 = nirp.pkg.feedStream(pkg42,"F1") ;
first42cp = nirp.units.cstr(struct('V',1),feed42,rs42) ;
out42cp = nirp.units.pfr(struct('V',1,'D',0.1),first42cp,rs42) ;
diagram42cp = simulateValidationExample(files(10),"ex10_problem42_cstr_pfr") ;
first42pc = nirp.units.pfr(struct('V',1,'D',0.1),feed42,rs42) ;
out42pc = nirp.units.cstr(struct('V',1),first42pc,rs42) ;
diagram42pc = simulateValidationExample(files(11),"ex11_problem42_pfr_cstr") ;

pkg19 = nirp.pkg.examples.problem19Gas() ;
rs19 = nirp.pkg.toReactionSys(pkg19) ; feed19 = nirp.pkg.feedStream(pkg19,"F1") ;
out19 = nirp.units.pfr(struct('V',1.5,'D',0.1,'heatMode','Adiabatic'), ...
    feed19,rs19) ;
diagram19 = simulateValidationExample(files(12),"ex12_problem19_adiabatic_pfr") ;

pkg44 = nirp.pkg.readDictionary(replace(files(7),".slx",".sldd")) ;
rs44 = nirp.pkg.toReactionSys(pkg44) ; feed44 = nirp.pkg.feedStream(pkg44,"F1") ;
out44single = nirp.units.cstr(struct('V',0.5,'heatMode','Adiabatic', ...
    'initialTemperatureGuess',495),feed44,rs44) ;
first44 = nirp.units.cstr(struct('V',0.25,'heatMode','Adiabatic', ...
    'initialTemperatureGuess',490),feed44,rs44) ;
out44series = nirp.units.cstr(struct('V',0.25,'heatMode','Adiabatic', ...
    'initialTemperatureGuess',499),first44,rs44) ;
diagram44 = simulateValidationExample(files(7),"ex7_problem44c") ;

pkg21 = nirp.pkg.examples.problem21Gas() ;
rs21 = nirp.pkg.toReactionSys(pkg21) ; feed21 = nirp.pkg.feedStream(pkg21,"F1") ;
temperature21a = fzero(@(temperature) pfrConversionAtTemperature( ...
    temperature,feed21,rs21,'Isothermal')-0.9,[330 450]) ;
temperature21b = fzero(@(temperature) pfrConversionAtTemperature( ...
    temperature,feed21,rs21,'Adiabatic')-0.9,[380 520]) ;
diagram21a = simulateValidationExample(files(13), ...
    "ex13_problem21a_isothermal_pfr") ;
diagram21b = simulateValidationExample(files(14), ...
    "ex14_problem21b_adiabatic_pfr") ;

pkg27 = nirp.pkg.examples.problem27Jacketed() ;
rs27 = nirp.pkg.toReactionSys(pkg27) ; feed27 = nirp.pkg.feedStream(pkg27,"F1") ;
temperature27 = fzero(@(temperature) cstr27ConversionAtTemperature( ...
    temperature,feed27,rs27)-0.8,[285 305]) ;
diagram27 = simulateValidationExample(files(15), ...
    "ex15_problem27_jacketed_cstr") ;

pkg30 = nirp.pkg.examples.problem30Liquid() ;
rs30 = nirp.pkg.toReactionSys(pkg30) ;
feedPO = nirp.pkg.feedStream(pkg30,"Feed PO") ;
feedW = nirp.pkg.feedStream(pkg30,"Feed W") ;
mixed30 = nirp.units.mixer([],{feedPO,feedW},rs30) ;
out30 = nirp.units.cstr(struct('V',1.136,'heatMode','Adiabatic'),mixed30,rs30) ;
out31 = nirp.units.cstr(struct('V',1.136,'heatMode','Other', ...
    'U',567.7,'A',3.7,'utilityTin',302.65),mixed30,rs30) ;
diagram30 = simulateValidationExample(files(16), ...
    "ex16_problem30_adiabatic_cstr") ;
diagram31 = simulateValidationExample(files(17), ...
    "ex17_problem31_cooled_cstr") ;

pkg44a = nirp.pkg.examples.problem44Liquid() ;
rs44a = nirp.pkg.toReactionSys(pkg44a) ; feed44a = nirp.pkg.feedStream(pkg44a,"F1") ;
volume44pfr = fzero(@(volume) reactorConversion(feed44a, ...
    nirp.units.pfr(struct('V',volume,'D',0.1,'heatMode','Adiabatic'), ...
    feed44a,rs44a),1)-0.85,[0.005 0.1]) ;
volume44cstr = fzero(@(volume) reactorConversion(feed44a, ...
    nirp.units.cstr(struct('V',volume,'heatMode','Adiabatic'), ...
    feed44a,rs44a),1)-0.85,[0.01 0.03]) ;
diagram44a = simulateValidationExample(files(18),"ex18_problem44a_volumes") ;

pkg45 = nirp.pkg.examples.problem45Liquid() ;
rs45 = nirp.pkg.toReactionSys(pkg45) ; feed45 = nirp.pkg.feedStream(pkg45,"F1") ;
volume45 = fzero(@(volume) threeCstrConversion(volume,feed45,rs45)-0.9, ...
    [0.1 0.5]) ;
temperature45 = fzero(@(temperature) cstr45OutletTemperature( ...
    temperature,feed45,rs45)-368.15,[335 355]) ;
diagram45a = simulateValidationExample(files(19), ...
    "ex19_problem45a_three_cstrs") ;
diagram45b = simulateValidationExample(files(20), ...
    "ex20_problem45b_feed_temperature") ;

pkg17 = nirp.pkg.examples.problem17AdiabaticGas() ;
rs17 = nirp.pkg.toReactionSys(pkg17) ; feed17 = nirp.pkg.feedStream(pkg17,"F1") ;
volume17 = fzero(@(volume) pfrVolumeConversion( ...
    volume,feed17,rs17,'Adiabatic')-0.35,[0.001 0.1]) ;
diagram17 = simulateValidationExample(files(21), ...
    "ex21_problem17_adiabatic_pfr_volume") ;

pkg18 = nirp.pkg.examples.problem18AcetoneCracking() ;
rs18 = nirp.pkg.toReactionSys(pkg18) ; feed18 = nirp.pkg.feedStream(pkg18,"F1") ;
volume18 = fzero(@(volume) pfrVolumeConversion( ...
    volume,feed18,rs18,'Adiabatic')-0.2,[0.1 10]) ;
diagram18 = simulateValidationExample(files(22), ...
    "ex22_problem18_acetone_cracking") ;

pkg23 = nirp.pkg.examples.problem23ButaneIsomerization() ;
rs23 = nirp.pkg.toReactionSys(pkg23) ; feed23 = nirp.pkg.feedStream(pkg23,"F1") ;
volume23 = fzero(@(volume) pfrVolumeConversion( ...
    volume,feed23,rs23,'Adiabatic')-0.65,[0.2 5]) ;
diagram23 = simulateValidationExample(files(23), ...
    "ex23_problem23_butane_isomerization") ;

pkg26 = nirp.pkg.examples.problem26ScaleUpGas() ;
rs26 = nirp.pkg.toReactionSys(pkg26) ; feed26 = nirp.pkg.feedStream(pkg26,"F1") ;
volume26 = fzero(@(volume) cstrVolumeConversion( ...
    volume,feed26,rs26,'Isothermal')-0.75,[100 3000]) ;
diagram26 = simulateValidationExample(files(24), ...
    "ex24_problem26_scale_up_cstr") ;

pkg38 = nirp.pkg.examples.problem38ParallelGas() ;
rs38 = nirp.pkg.toReactionSys(pkg38) ; feed38 = nirp.pkg.feedStream(pkg38,"F1") ;
volume38 = fzero(@(volume) parallelPfrConversion(volume,feed38,rs38)-0.8, ...
    [0.005 0.2]) ;
diagram38 = simulateValidationExample(files(25), ...
    "ex25_problem38_parallel_pfrs") ;

pkg40c = nirp.pkg.examples.problem40cGas() ;
rs40c = nirp.pkg.toReactionSys(pkg40c) ; feed40c = nirp.pkg.feedStream(pkg40c,"F1") ;
volume40c = fzero(@(volume) pfrVolumeConversion( ...
    volume,feed40c,rs40c,'Isothermal')-0.6,[0.01 0.1]) ;
diagram40c = simulateValidationExample(files(26), ...
    "ex26_problem40c_pfr_volume") ;

pkg49 = nirp.pkg.examples.problem49AdiabaticLiquid() ;
rs49 = nirp.pkg.toReactionSys(pkg49) ; feed49 = nirp.pkg.feedStream(pkg49,"F1") ;
volume49a = fzero(@(volume) twoCstrConversion(volume,feed49,rs49)-0.8, ...
    [0.5 5]) ;
volume49b = fzero(@(volume) cstrVolumeConversion( ...
    volume,feed49,rs49,'Adiabatic')-0.8,[1 20]) ;
diagram49a = simulateValidationExample(files(27), ...
    "ex27_problem49a_two_adiabatic_cstrs") ;
diagram49b = simulateValidationExample(files(28), ...
    "ex28_problem49b_one_adiabatic_cstr") ;

pkg34 = nirp.pkg.examples.problem34dMonsanto() ;
rs34 = nirp.pkg.toReactionSys(pkg34) ; feed34 = nirp.pkg.feedStream(pkg34,"F1") ;
out34 = nirp.units.cstr(struct('V',1.5,'heatMode','Other', ...
    'U',35.85*4184/60,'A',1,'utilityTin',298.15, ...
    'initialTemperatureGuess',1050),feed34,rs34) ;
diagram34 = simulateValidationExample(files(29), ...
    "ex29_problem34d_jacketed_cstr") ;

% T-121: cooled, fast reversible gas CSTR (problem 33b).
pkg33 = nirp.pkg.examples.problem33Gas() ;
rs33 = nirp.pkg.toReactionSys(pkg33) ; feed33 = nirp.pkg.feedStream(pkg33,"F1") ;
out33 = nirp.units.cstr(struct('V',1.6,'heatMode','Other', ...
    'U',10,'A',2,'utilityTin',290.15),feed33,rs33) ;
diagram33 = simulateValidationExample(files(30), ...
    "ex30_problem33b_cooled_gas_cstr") ;

problem = ["P37a";"P37a";"P37a";"P40a";"P40b";"P42";"P42"; ...
    "P19";"P19";"P44c";"P44c";"P21a";"P21b";"P27"; ...
    "P30";"P30";"P31";"P31";"P44a";"P44a";"P45a";"P45b"; ...
    "P17";"P18";"P23";"P26";"P38";"P40c";"P49a";"P49b"; ...
    "P34d";"P34d";"P33b";"P33b"] ;
magnitude = ["C_A1 (mol/L)";"C_A2 (mol/L)";"X_A";"X_A";"X_A"; ...
    "X (CSTR+PFR)";"X (PFR+CSTR)";"X_A";"T_out (K)"; ...
    "X_A (one CSTR)";"X_A (two CSTRs)";"Adjusted T (K)"; ...
    "Adjusted T (K)";"Adjusted T (K)";"T_out (K)";"X_PO"; ...
    "T_out (K)";"X_PO";"Adjusted PFR V (L)";"Adjusted CSTR V (L)"; ...
    "Adjusted V per CSTR (L)";"Adjusted feed T (K)"; ...
    "Adjusted PFR V (L)";"Adjusted PFR V (m^3)"; ...
    "Adjusted PFR V (m^3)";"Adjusted CSTR V (m^3)"; ...
    "Adjusted V per PFR (L)";"Adjusted PFR V (L)"; ...
    "Adjusted V per CSTR (m^3)";"Adjusted CSTR V (m^3)"; ...
    "T_out (K)";"X_A";"T_out (K)";"X_A"] ;
diagram = [concentrationInMolPerL(diagram37.Streams.CSTR1Outlet.streamSI,1); ...
    concentrationInMolPerL(diagram37.Streams.Product.streamSI,1); ...
    diagram37.Streams.Product.conversion;diagram40a.Streams.Product.conversion; ...
    diagram40b.Streams.Product.conversion;diagram42cp.Streams.Product.conversion; ...
    diagram42pc.Streams.Product.conversion;diagram19.Streams.Product.conversion; ...
    diagram19.Streams.Product.streamSI.T;diagram44.Streams.Product500.conversion; ...
    diagram44.Streams.ProductSeries.conversion; ...
    diagram21a.Streams.F1.streamSI.T;diagram21b.Streams.F1.streamSI.T; ...
    diagram27.Streams.F1.streamSI.T;diagram30.Streams.Product.streamSI.T; ...
    diagram30.Streams.Product.conversion;diagram31.Streams.Product.streamSI.T; ...
    diagram31.Streams.Product.conversion; ...
    diagnosticVolume(diagram44a,"ex18_problem44a_volumes","PFR")*1000; ...
    diagnosticVolume(diagram44a,"ex18_problem44a_volumes","CSTR")*1000; ...
    diagnosticVolume(diagram45a,"ex19_problem45a_three_cstrs","CSTR 1")*1000; ...
    diagram45b.Streams.F1.streamSI.T; ...
    diagnosticVolume(diagram17,"ex21_problem17_adiabatic_pfr_volume","PFR")*1000; ...
    diagnosticVolume(diagram18,"ex22_problem18_acetone_cracking","PFR"); ...
    diagnosticVolume(diagram23,"ex23_problem23_butane_isomerization","PFR"); ...
    diagnosticVolume(diagram26,"ex24_problem26_scale_up_cstr","CSTR"); ...
    diagnosticVolume(diagram38,"ex25_problem38_parallel_pfrs","PFR 1")*1000; ...
    diagnosticVolume(diagram40c,"ex26_problem40c_pfr_volume","PFR")*1000; ...
    diagnosticVolume(diagram49a,"ex27_problem49a_two_adiabatic_cstrs","CSTR 1"); ...
    diagnosticVolume(diagram49b,"ex28_problem49b_one_adiabatic_cstr","CSTR"); ...
    diagram34.Streams.Product.streamSI.T;diagram34.Streams.Product.conversion; ...
    diagram33.Streams.Product.streamSI.T;diagram33.Streams.Product.conversion] ;
script = [concentrationInMolPerL(first37,1);concentrationInMolPerL(out37,1); ...
    conversion(feedA,out37,1);conversion(feed40,out40a,1); ...
    conversion(feed40,out40b,1);conversion(feed42,out42cp,1); ...
    conversion(feed42,out42pc,1);conversion(feed19,out19,1);out19.T; ...
    conversion(feed44,out44single,1);conversion(feed44,out44series,1); ...
    temperature21a;temperature21b;temperature27;out30.T; ...
    conversion(feedPO,out30,1);out31.T;conversion(feedPO,out31,1); ...
    volume44pfr*1000;volume44cstr*1000;volume45*1000;temperature45; ...
    volume17*1000;volume18;volume23;volume26;volume38*1000;volume40c*1000; ...
    volume49a;volume49b;out34.T;conversion(feed34,out34,1); ...
    out33.T;conversion(feed33,out33,1)] ;
official = [0.828;0.704;0.296;0.663;0.578;0.464;0.472;0.600; ...
    779.53;0.977;0.995;387;433;298.3;340.45;NaN;310.75;0.31; ...
    30.5;17.6;250.5;346.8;20.3;1.03;1.23;816.7;32.1;56.0; ...
    1.10;4.76;1067.95;0.371;772.6;0.869] ;
difference = abs(diagram-official) ;
note = strings(size(problem)) ;
note(problem == "P30" | problem == "P31") = ...
    "Known difference: graphical official solution" ;
note(problem == "P27") = ...
    "Hand check of the statement data gives 298.62 K (official 298.3 K)" ;
note(problem == "P34d" & magnitude == "T_out (K)") = ...
    "Known 0.5 K difference from the graphical official solution" ;
validation = table(problem,magnitude,diagram,script,official,difference,note, ...
    'VariableNames',{'Problem','Magnitude','Diagram','Script','Official', ...
    'Difference','Note'}) ;
disp(validation) ;
relative = abs(diagram-script)./max(abs(script),1e-15) ;
adjusted = ismember(problem,["P21a","P21b","P27","P44a","P45a","P45b", ...
    "P17","P18","P23","P26","P38","P40c","P49a","P49b"]) ;
assert(all(relative(~adjusted) <= 1e-9),'nirp:validation:mismatch', ...
    'A non-adjusted diagram differs from its script result by more than 1e-9.') ;
assert(all(relative(adjusted) <= 1e-5),'nirp:validation:adjustMismatch', ...
    'An adjusted parameter differs from its fzero result by more than 1e-5.') ;

function results = simulateValidationExample(file,name)
    evalin('base','clear nirpResults') ;
    load_system(char(file)) ; sim(char(name)) ;
    results = evalin('base','nirpResults') ;
    close_system(char(name),0) ; Simulink.data.dictionary.closeAll('-discard') ;
end

function value = concentrationInMolPerL(stream,index)
    concentrations = nirp.stream.concentration(stream) ;
    value = concentrations(index)/1000 ;
end

function value = conversion(feed,product,index)
    value = (feed.F(index)-product.F(index))/feed.F(index) ;
end

function value = reactorConversion(feed,product,index)
    value = conversion(feed,product,index) ;
end

function stream = atTemperature(stream,temperature)
    stream.T = temperature ;
    stream = nirp.stream.refresh(stream) ;
end

function value = pfrConversionAtTemperature(temperature,feed,rs,heatMode)
    inlet = atTemperature(feed,temperature) ;
    product = nirp.units.pfr(struct('V',1,'D',0.1, ...
        'heatMode',heatMode),inlet,rs) ;
    value = conversion(inlet,product,1) ;
end

function value = cstr27ConversionAtTemperature(temperature,feed,rs)
    inlet = atTemperature(feed,temperature) ;
    product = nirp.units.cstr(struct('V',0.2,'heatMode','Other', ...
        'U',300,'A',9,'utilityTin',273),inlet,rs) ;
    value = conversion(inlet,product,1) ;
end

function value = threeCstrConversion(volume,feed,rs)
    params = struct('V',volume,'heatMode','Specified T','specifiedT',368.15) ;
    first = nirp.units.cstr(params,feed,rs) ;
    second = nirp.units.cstr(params,first,rs) ;
    product = nirp.units.cstr(params,second,rs) ;
    value = conversion(feed,product,1) ;
end

function value = cstr45OutletTemperature(temperature,feed,rs)
    inlet = atTemperature(feed,temperature) ;
    product = nirp.units.cstr(struct('V',0.250480335, ...
        'heatMode','Adiabatic'),inlet,rs) ;
    value = product.T ;
end

function value = diagnosticVolume(results,model,block)
    field = matlab.lang.makeValidName(model+"_"+block) ;
    value = results.Diagnostics.(field).lastInfo.V ;
end

function value = pfrVolumeConversion(volume,feed,rs,heatMode)
    product = nirp.units.pfr(struct('V',volume,'D',0.1, ...
        'heatMode',heatMode),feed,rs) ;
    value = conversion(feed,product,1) ;
end

function value = cstrVolumeConversion(volume,feed,rs,heatMode)
    product = nirp.units.cstr(struct('V',volume,'heatMode',heatMode),feed,rs) ;
    value = conversion(feed,product,1) ;
end

function value = parallelPfrConversion(volume,feed,rs)
    branches = nirp.units.splitter(struct('fractions',[0.5 0.5]),feed,rs) ;
    first = nirp.units.pfr(struct('V',volume,'D',0.1),branches{1},rs) ;
    second = nirp.units.pfr(struct('V',volume,'D',0.1),branches{2},rs) ;
    product = nirp.units.mixer([],{first,second},rs) ;
    value = conversion(feed,product,1) ;
end

function value = twoCstrConversion(volume,feed,rs)
    params = struct('V',volume,'heatMode','Adiabatic') ;
    first = nirp.units.cstr(params,feed,rs) ;
    product = nirp.units.cstr(params,first,rs) ;
    value = conversion(feed,product,1) ;
end

function restoreValidationEnvironment(config,generatedFolder,validationFolder)
    bdclose('all') ; Simulink.data.dictionary.closeAll('-discard') ;
    Simulink.fileGenControl('setConfig','config',config) ;
    if contains([path pathsep],[validationFolder pathsep]), rmpath(validationFolder) ; end
    if isfolder(generatedFolder), rmdir(generatedFolder,'s') ; end
    if isfolder(validationFolder), rmdir(validationFolder,'s') ; end
end
