function validate(s,nComp)
%VALIDATE Validate the fixed NIRP stream structure and optional component count.
%   All physical quantities are SI. Invalid input raises nirp:stream:invalid.
% =========================================================================
% Javier Berenguer Sabater
% Created: October 1, 2026. Last update: October 1, 2026
% =========================================================================

    expected = {'F';'T';'P';'phase';'Q';'status'} ;
    if ~isstruct(s) || ~isscalar(s) || ~isequal(fieldnames(s),expected)
        error('nirp:stream:invalid', ...
            'Stream must be a scalar struct with fields F, T, P, phase, Q, status in that order.') ;
    end
    if ~isnumeric(s.F) || ~isreal(s.F) || ~iscolumn(s.F) || isempty(s.F) || ...
            any(~isfinite(s.F)) || any(s.F < 0)
        error('nirp:stream:invalid', ...
            'F must be a nonempty, finite, nonnegative numeric column.') ;
    end
    if nargin >= 2 && (~isnumeric(nComp) || ~isscalar(nComp) || ...
            nComp < 1 || nComp ~= fix(nComp) || numel(s.F) ~= nComp)
        error('nirp:stream:invalid', ...
            'Stream component count does not match nComp.') ;
    end
    if ~isnumeric(s.T) || ~isreal(s.T) || ~isscalar(s.T) || ...
            ~isfinite(s.T) || s.T <= 0 || ...
            ~isnumeric(s.P) || ~isreal(s.P) || ~isscalar(s.P) || ...
            ~isfinite(s.P) || s.P <= 0
        error('nirp:stream:invalid', ...
            'T (K) and P (Pa) must be finite positive scalars.') ;
    end
    if ~isnumeric(s.phase) || ~isreal(s.phase) || ~isscalar(s.phase) || ...
            ~ismember(s.phase,[0 1]) || ...
            ~isnumeric(s.Q) || ~isreal(s.Q) || ~isscalar(s.Q) || ...
            ~isfinite(s.Q) || s.Q < 0
        error('nirp:stream:invalid', ...
            'phase must be 0 or 1 and Q must be a finite nonnegative scalar.') ;
    end
    if ~isnumeric(s.status) || ~isreal(s.status) || ~isscalar(s.status) || ...
            ~ismember(s.status,[-1 0 1])
        error('nirp:stream:invalid', ...
            'status must be scalar -1, 0, or 1.') ;
    end
    if s.status == 0 && (any(s.F ~= 0) || s.Q ~= 0)
        error('nirp:stream:invalid', ...
            'An empty stream (status 0) must have zero F and Q.') ;
    elseif s.status ~= 0 && any(s.F > 0) && s.Q <= 0
        error('nirp:stream:invalid', ...
            'A nonempty stream with nonzero F must have positive Q.') ;
    end
    if s.phase == 1
        expectedQ = sum(s.F)*8.314*s.T/s.P ;
        tolerance = 1e-12*max(1,abs(expectedQ)) ;
        if abs(s.Q-expectedQ) > tolerance
            error('nirp:stream:invalid', ...
                'Gas Q must equal sum(F)*8.314*T/P.') ;
        end
    end
end
